### ISSUE TITLE
Parse date/time formats

### ISSUE THREAD

**Issue by hadley** [hadley/haven#10]

**Comment by hadley** [comment]
* Update ReadStat to get latest behaviour
* Add POSIX support to TimeFormatStrings

**Comment by hadley** [comment]
@afleishman since you're interested, is there any chance you could make me a sav file containing date times with one column for each date-time type?

**Comment by afleishman** [comment]
Of course. I created this file using write_sav. There are three columns -- First, is date type, next is POSIXct, and finally character. Let me know if you need anything else!

https://github.com/afleishman/spss/blob/0244b4836c63adff180cbf65ec0a9182733fc19b/test_haven.sav

**Comment by hadley** [comment]
@afleishman can you please create with spss? (not haven, since that's what I'm trying to test)

**Comment by afleishman** [comment]
https://github.com/afleishman/spss/blob/master/test_spss.sav

**Comment by hadley** [comment]
@afleishman could you add a column with a time variable please?

**Comment by afleishman** [comment]
https://github.com/afleishman/spss/blob/master/test_time_spss.sav

first column type: Date (mm/dd/yyyy)
second column type: Date (dd-mmmm-yyyy hh:mm:ss)
third column type: Date (hh:mm:ss.ss)

**Comment by hadley** [comment]
I'm currently getting 

```R
        date            date.posix     time
1 2014-09-22 201416-09-22 00:00:00 12:11:10
2 2014-09-23   2014-09-23 15:59:20 15:59:20
```

And I suspect that the first date.posix is incorrect. What is it supposed to be?

@evanmiller any thoughts on why only the first value is getting read incorrectly?

**Comment by afleishman** [comment]
Actually, it was a typo on my part... what you've produced is correct. Sorry about that.

**Comment by hadley** [comment]
In that case, awesome :)
