### ISSUE TITLE
Return values requre  a lot of cleanup

### ISSUE THREAD

**Issue by izahn** [hadley/haven#106]
I've been kicking the tires on haven, and am really happy to see a fast and modern package for importing data from other statistical packages. Thanks to Hadley and everyone else who contributed for all their hard work! It is very nice indeed to have a package that reliably imports Stata version > 12 data sets. 

I have encountered a number of difficulties using the package, which I have tried to illustrate and describe at https://gist.github.com/izahn/db16d52ed6b4289425bb. In one way or another I think these all involve the decision to store metadata as variable-level attributes rather than as data.frame level attributes as the foreign package does. 

Specifically:
1. Using `str` on data read with haven is not as useful because the attributes make the output very noisy, and because everything just says "atomic" rather than providing information about the variable type.
2. Cleaning up data imported with haven is not easy because it doesn't appear to try to work out what type each column should be. Rather it seems to store everything as a double along with the metadata, and leaves it to the user to sort out. This is somewhat ironic, since one purpose of metadata is to provide information to the computer so that it can represent the data appropriately.

I realize these are somewhat broad points, and I don't have a sense of how difficult it would be to address these issues. I don't know C, but I'm happy to help with R coding, testing, or anything else I can do to help make haven more user-friendly.

**Comment by izahn** [comment]
There is now an option in the `rio` package to clean up the meta data returned by `read_dta`, `read_spss` etc. (see https://github.com/leeper/rio/blob/master/R/utils.R#L86). Can this be incorporated into haven in some form? It would be nice to be able to use this package without needing to do so much post-import cleanup.

**Comment by hadley** [comment]
1. Using data frame level attributes is absolutely the wrong thing to do because the attributes belong to the individual columns, not the data frame as a whole.

2. I don't understand what you mean because haven definitely loads different variable types and has tests to prove it. I'd recommend filing individual bugs about specific issues.
