### ISSUE TITLE
write_sav and strings with > 256 characters?

### ISSUE THREAD

**Issue by itsdalmo** [hadley/haven#107]
Not sure if this is a bug or a feature, but `write_sav` seems to have a max string length of 256 character vectors and truncates the rest without warning. A quick example that produces a error in the latest version (`0.2.0.9000`):

    test_that("can roundtrip long strings", {
      x <- paste0(rep(letters, 10), collapse = "")
      expect_equal(roundtrip_var(x), x)
    })

Since both SPSS and R can store strings that are longer than 256 characters, is this some limitation in the underlying C++ code or a design choice?

**Comment by evanmiller** [comment]
This is something of a design choice in ReadStat. String longer than 255 characters require a special kind of storage in SAV files ("Very Long String Records") which have not been implemented by us.

**Comment by itsdalmo** [comment]
Thank you for clearing this up Evan. Will these be implemented in a future version? (If so, ETA?)

**Comment by evanmiller** [comment]
If I receive a patch from someone, then yes, but I don't have specific plans to implement it myself.

**Comment by evanmiller** [comment]
Just so you know I am in the process of implementing this feature. You can follow along here:

https://github.com/WizardMac/ReadStat/issues/72
