### ISSUE TITLE
as_factor has odd behaviour when applied to zeros

### ISSUE THREAD

**Issue by jon-mellon** [hadley/haven#112]
I have some data where many data values are zero as a meaningful category and this is labelled. There seems to be some kind of unexpected behaviour when  apply as_factor to a labelled vector with zero values. This behaviour seems to come and go, so I'm not sure if this example will definitely reproduce. 

    library(haven)
    x <- labelled(c(0, 1, 1,0 ), c(Bad = 0, Good = 1))
The vector appears to have been created correctly here:

<Labelled>
[1] 0 1 1 0
Labels:
 Bad Good 
   0    1 
However conversion to factor gives just about the worst possible outcome:

       as_factor(x)

[1] Good NA NA Good
Levels: Bad Good

**Comment by jon-mellon** [comment]
In the meantime, a convenience function I've written seems to give the correct answer:

    asFactor <- function(x) {
       factor(names(attributes(x)$labels)[match(x, attributes(x)$labels)], levels = names(attributes(x)$labels))
    }
    asFactor(x)

**Comment by tklebel** [comment]
Did you update to the latest (dev)-version of `haven`? With version `0.2.0.9000` (hash: `8f65dbc289`) I don't encounter that bug any more (I believe it was a bug that got fixed).

Using `devtools::install_github("hadley/haven")` will resolve your issue.

**Comment by larmarange** [comment]
Did you try to_factor function in labelled package?

**Comment by lottaholm** [comment]
I experience this same issue with haven version 0.2.1 downloaded two days ago. My (significant) zeros turn into NA:s when converted using as_factor.
