### ISSUE TITLE
AIX bug: "Error: cannot allocate vector of size 78 Kb"

### ISSUE THREAD

**Issue by vinhdizzo** [hadley/haven#113]
Hi,

I generated a 700mb sas data set using
```{sas}
data libfoo.bar ;
	call streaminit(123);
	array x{10000} x1-x10000 ;
	do i=1 to 26750 ;
		do j=1 to dim(x) ;
			x(j) = rand('Uniform') ;
		end ;
		output ;
	end ;
run ;
```

When loading the data in R 3.2.2 with haven-dev, I get the following error:
```{r}
> library(haven)
> d1 = read_sas('bar.sas7bdat')
Error: cannot allocate vector of size 78 Kb
```

I posted the issue over in ReadStat [here](https://github.com/WizardMac/ReadStat/issues/33) but it appears to be a bug in haven.  Thanks.

**Comment by evanmiller** [comment]
As referenced in the ReadStat issue, this issue appears to manifest itself as a segfault in some cases. Both the segfault and the "cannot allocate vector" messages occur inside haven's variable handler.

**Comment by evanmiller** [comment]
Sample output (including debug messages from ReadStat):

```
Initializing variable...
Calling variable handler on variable 1013...

 *** caught segfault ***
address 4, cause 'invalid permissions'
```

**Comment by evanmiller** [comment]
@vinhdizzo Do you have very long variable labels by any chance? Say >1024 bytes?

**Comment by evanmiller** [comment]
If I had to guess I'd say the segfault and error message come from this line:

https://github.com/hadley/haven/blob/master/src/DfReader.cpp#L145

Wondering if there's either an encoding issue or NUL-termination issue.

**Comment by vinhdizzo** [comment]
The original post (700mb) did not have any labels.  Variables were x1-x10000.  The data set that segfaulted (bar_little_endian.sas7bdat) also did not have any labels.  Same variable names

**Comment by evanmiller** [comment]
Thanks for the additional info. It could be ReadStat is passing invalid data to haven, or thinking there's a (garbage) variable label when there is actually none. Haven appears to create vectors (explicitly or implicitly) in several parts of the code, so I'm not entirely certain where this bug is getting triggered. From the looks of it, could be the name, # of rows, or variable label. I'll try to prepare a ReadStat patch with a bit more debug information.

And to be clear, this problem is only occurring for you on AIX -- and not on Windows?

**Comment by vinhdizzo** [comment]
Yes, only on AIX.

**Comment by evanmiller** [comment]
Please try this and tell me the last several lines of the log: [readstat_sas.c](https://gist.githubusercontent.com/evanmiller/243ba5519bdb393e130e/raw/8a7d761261a1f325b2c07716add75b15d45e87ae/readstat_sas.c)

**Comment by vinhdizzo** [comment]
```{r}
Submitting variable #1103 named x1103

+ Variable label:

+ Variable format:

Submitting variable #1104 named x1104

+ Variable label:

+ Variable format:

Submitting variable #1105 named x1105

+ Variable label:

+ Variable format:

Submitting variable #1106 named x1106

+ Variable label:

+ Variable format:


 *** caught segfault ***
```

**Comment by evanmiller** [comment]
Try this: [DfReader.cpp](https://gist.githubusercontent.com/evanmiller/087e395f785029d1a8e6/raw/25caa36fa4fa131f43c60b3b8b0884d5f5be1258/DfReader.cpp)

**Comment by vinhdizzo** [comment]
```{r}
Retrieving name of variable...
+ Name is x1104
+ Getting label...
++ Setting value labels...
++ Value labels set to
+ Getting format...
Submitting variable #1105 named x1105

+ Variable label:

+ Variable format:

Retrieving name of variable...
+ Name is x1105
+ Getting label...
++ Setting value labels...
++ Value labels set to
+ Getting format...
Submitting variable #1106 named x1106

+ Variable label:

+ Variable format:

Retrieving name of variable...
+ Name is x1106

 *** caught segfault ***
address 4, cause 'invalid permissions'
```

**Comment by evanmiller** [comment]
What is the data type of x1106? Text or numeric?

**Comment by evanmiller** [comment]
In the meantime, try this: [DfReader.cpp](https://gist.githubusercontent.com/evanmiller/087e395f785029d1a8e6/raw/b90cfc7c386d80d302642718041c3191fc138578/DfReader.cpp)

**Comment by vinhdizzo** [comment]
They are all numeric.  Random uniform data.

**Comment by evanmiller** [comment]
Ok, that narrows down the crash to this line:

https://github.com/hadley/haven/blob/master/src/DfReader.cpp#L137

**Comment by vinhdizzo** [comment]
```{r}
Retrieving name of variable...
+ Name is x1105
+ Creating vector with 27500rows...
+ Getting label...
Submitting variable #1106 named x1106

+ Variable label:

+ Variable format:

Retrieving name of variable...
+ Name is x1106
+ Creating vector with 27500rows...
+ Getting label...
Submitting variable #1107 named x1107

+ Variable label:

+ Variable format:

Retrieving name of variable...
+ Name is x1107
+ Creating vector with 27500rows...
+ Getting label...
Submitting variable #1108 named x1108

+ Variable label:

+ Variable format:

Retrieving name of variable...
+ Name is x1108
+ Creating vector with 27500rows...
+ Getting label...
Submitting variable #1109 named x1109

+ Variable label:

+ Variable format:

Retrieving name of variable...
+ Name is x1109
+ Creating vector with 27500rows...

 *** caught segfault ***
address 4, cause 'invalid permissions'
aborting ...
```

**Comment by evanmiller** [comment]
Try this: [DfReader.cpp](https://gist.githubusercontent.com/evanmiller/087e395f785029d1a8e6/raw/ebfc3ae8fbb4dc10e8231e7f1ec93f3abe6c151a/DfReader.cpp)

**Comment by vinhdizzo** [comment]
```{r}
Retrieving name of variable #1108/10002...
+ Name is x1108
+ Creating vector with 27500 rows...
Submitting variable #1109 named x1109

+ Variable label:

+ Variable format:

Retrieving name of variable #1109/10002...
+ Name is x1109
+ Creating vector with 27500 rows...

 *** caught segfault ***
address 4, cause 'invalid permissions'
```

**Comment by evanmiller** [comment]
Is it possible you are running out of memory somehow? (Maybe a per-process memory limit?) This would still surprise me as the amount of memory needed is only 27500 * 1109 * 8 = 244 MB.

**Comment by vinhdizzo** [comment]
I'm not sure why I would run out of memory.  Total memory is 256GB on the system.  Yes, other processes do make use of them.  I recall successfully loading large data sets (csv) in the past.

**Comment by evanmiller** [comment]
At this point I am stumped. The call to NumericVector(nrows_) is failing with a fairly small argument. The only other thing I can think of is that a bug somewhere else is creating a very large vector which hogs all the system memory, and then this small allocation is failing. I'm not really happy with that explanation as the code appears to be segfaulting on exactly the same variable every time, and out-of-memory problems are usually more random. Also, you'd probably notice the system grinding to a standstill.

I've tried hunting down the source code for NumericVector but it appears to be implemented with C++ templates and hard to grep for. I'm afraid we will need a C++ / Rcpp whiz to get to the bottom of this one :-/

**Comment by vinhdizzo** [comment]
Hmm, how about we focus on the 700mb file that did not segfault?  Here's what I get:
```{r}
Retrieving name of variable #3048/10002...
+ Name is x3048
+ Creating vector with 10000 rows...
Submitting variable #3049 named x3049

+ Variable label:

+ Variable format:

Retrieving name of variable #3049/10002...
+ Name is x3049
+ Creating vector with 10000 rows...
Submitting variable #3050 named x3050

+ Variable label:

+ Variable format:

Retrieving name of variable #3050/10002...
+ Name is x3050
+ Creating vector with 10000 rows...
Error: cannot allocate vector of size 78 Kb
```
Does it offer any clue?

**Comment by evanmiller** [comment]
It's a clue inasmuch as it appears to be very closely related. What is likely happening is a Very Large Vector is being requested somewhere deep in the bowels of R. There are checks before the allocation happens, and if those checks fail, you get the "cannot allocate vector" error. If the checks succeed -- but the operating system cannot fulfill the request -- a NULL pointer is returned in place of the vector, and a segfault occurs.

I'll poke around some more and report back.

**Comment by vinhdizzo** [comment]
What I'm also going to do is write the file out as a delimited file and see if I could load it using read.table.  If that fails, then it may support your hunch about the memory limitations.

I compiled this R on AIX, and it could be that something went wrong.

**Comment by evanmiller** [comment]
Actually, can you try an older version of R? It looks like they've been messing with the memory allocator lately. I have 2.15 on my hard drive and the source code looks a lot different (and simpler) than the most recent release.

**Comment by vinhdizzo** [comment]
Hmm, I would need to compile that on AIX.  Did it before, so could try.  Would the haven package compile and install fine in 2.15?  I know there were changes to package content from 2 -> 3.

In the mean time, I'm also going to test my previous hypothesis.  Have to run now but should have results in 2 hours (no R 2.15).

**Comment by evanmiller** [comment]
Sounds good. No idea about package stuff -- I'd say try haven with R 3.0.0 first.

**Comment by evanmiller** [comment]
Reading the code some more, another possibility is that R is getting tripped up by `size_t` issues on AIX the same way ReadStat was tripped up. (IIRC `size_t` was 32-bit in my testing of your AIX server.) So you might want to ensure that R (and haven) are being compiled as 64-bit.

**Comment by vinhdizzo** [comment]
The following suggests R was compiled as 32 bit on AIX, right?
```{r}
> .Machine$sizeof.pointer
[1] 4
```
See the [second](http://stackoverflow.com/questions/18091614/how-can-i-know-if-r-is-running-on-64-bits-versus-32) response.

**Comment by evanmiller** [comment]
Yep -- that means it's compiled as 32-bit. It may be worth filing a bug with R about this, as R should not segfault under any circumstances. In the meantime try recompiling as 64-bit to see if that fixes things.

**Comment by vinhdizzo** [comment]
It is most likely a 32-bit issue then.  Here's what I get reading a delimited file:
```{r}
> d1 = read.table('baz700mb.txt', header=TRUE, sep='|')

 *** caught segfault ***
address 4, cause 'invalid permissions'
```

Man, I think I previously compiled as 64 bit...and was toying around with stuff, then decided to wipe it clean and re-compiled, in which case I forgot to set it to 64 bit.  Hopefully this fixes it...

**Comment by vinhdizzo** [comment]
Finally got a working version of R 64 bit compiled on AIX.  It looks like the error is no longer there.

```{r}

Retrieving name of variable #10001/10002...
+ Name is i
+ Creating vector with 10000 rows...
Submitting variable #10002 named j

+ Variable label:

+ Variable format:

Retrieving name of variable #10002/10002...
+ Name is j
+ Creating vector with 10000 rows...
      user     system    elapsed
0.46043333 0.02468333 0.95225000
> dim(d1)
[1] 10000 10002
```

Thanks so much for your help!

**Comment by evanmiller** [comment]
Great to hear it's fixed now. I recommend filing a bug report with the R project, as this is a significant bug in R:

https://bugs.r-project.org/bugzilla3/

The triggering example you gave with `read.table` should be sufficient for them to take interest.

**Comment by vinhdizzo** [comment]
Filed the bug [here](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16560).  Please take a look and add in your comments if you don't think it is sufficient.  Thanks!

**Comment by vinhdizzo** [comment]
Can you update the ReadStat repo to not output the 'Creating vector' log?  Thanks.

**Comment by vinhdizzo** [comment]
Please disregard the last request.  Sorry.

**Comment by evanmiller** [comment]
Yep the "master" branch is clean. The R bug report looks good to me -- hopefully they will act on it soon.

**Comment by evanmiller** [comment]
I guess the one thing I might test / add to the bug report is see if 32-bit R on Windows produces the same error -- they'll have a harder time reproducing on AIX.

**Comment by vinhdizzo** [comment]
I wouldnt think so...many would have reported such a windows error already :)

**Comment by evanmiller** [comment]
A fair point -- that's probably the first thing that the R core team will test anyway when they look at the report.

Onwards and upwards!
