### ISSUE TITLE
Invalid file error

### ISSUE THREAD

**Issue by jmurray1022** [hadley/haven#115]
On loading the SAS files for the 2014 NYTS I get an error about the associated cat file:

"Error: Failed to parse /Users/jared/Dropbox/nyts/nyts2014_formats.sas7bcat: Invalid file, or file has unsupported features."

The data itself appears to load fine, and I have every reason to think the cat file is valid  and works in SAS. The files are available at:

http://www.cdc.gov/tobacco/data_statistics/surveys/nyts/

**Comment by evanmiller** [comment]
Hi,

This appears to be a bug in [ReadStat](https://github.com/WizardMac/ReadStat) -- please re-file the issue over there and we can continue the discussion.

**Comment by jmurray1022** [comment]
Done (https://github.com/WizardMac/ReadStat/issues/38) thanks!
