### ISSUE TITLE
Multiple missings in SAS

### ISSUE THREAD

**Issue by gergness** [hadley/haven#117]
Using the development version of ReadStat, haven can now handle missing values in value labels from SAS much better than before.However because SAS has multiple values of missing (., .A, .B, etc.), I cannot get all of the data from SAS into R.

Here is a minimal example, the current behavior is pretty good, but the different forms of missing are squashed together, and there are NaNs in the value label.  Given that R only has one value for missing, I can see how this may actually be the best possible way to handle them. However, I thought I'd post this example in case it helps spur a better solution. Possibly it'd be better to drop the value labels with NaNs because they cannot be used and will just be junking up the factor levels.

Thanks!

``` r
library(haven)

data <- read_sas("https://dl.dropboxusercontent.com/u/2019891/haven_bug/formats_missing.sas7bdat", 
                 "https://dl.dropboxusercontent.com/u/2019891/haven_bug/formats_missing.sas7bcat")

data$variable
#> <Labelled>
#> [1]  1  2 NA NA
#> 
#> Labels:
#>  value   label is_na
#>    NaN REFUSED FALSE
#>      1     Yes FALSE
#>      2      No FALSE

as_factor(data$variable, dropNA = FALSE)
#> [1] Yes  No   <NA> <NA>
#> Levels: REFUSED Yes No

as_factor(data$variable)
#> [1] Yes  No   <NA> <NA>
#> Levels: REFUSED Yes No


# desired behavior
# as_factor(data$variable, dropNA = FALSE)
#> [1] Yes  No   REFUSED <NA>
#> Levels: REFUSED Yes No

# as_factor(data$variable)
#> [1] Yes  No   <NA>  <NA>
#> Levels: Yes No
```

**Comment by evanmiller** [comment]
Just so @hadley is aware, I've added a new function to the ReadStat API to extract the "tag" of a missing value:

```{C}
char readstat_value_tag(readstat_value_t value)
```

Although the values are nominally missing doubles (and `readstat_double_value` will return `NaN`), they might contain an alphabetic tag A-Z, which the above function returns.

Both Stata and SAS have tagged missings like this; so far only I've only implemented support for SAS catalog files. So if there is demand for tagged missings, I will need to implement support for them in SAS data files (as well as Stata .dta files) before R/haven can take advantage of them.

**Comment by evanmiller** [comment]
Turns out adding support for SAS data files wasn't too hard: https://github.com/WizardMac/ReadStat/commit/c4ab2b912ee3876128717756a23ec8cb0ac5e664

So it's just a question of what (if anything) haven would like to do with this tag information.

**Comment by evanmiller** [comment]
@hadley This issue should probably remain open -- the PR just added support on the C side, but there will need to be work (discussion) on the haven side to support multiple missings. (Unless of course this is a WONTFIX.)

**Comment by hadley** [comment]
Thanks - I need to spend a day or so and get my head around the best way to convert these various types of missing values into R data structures.

**Comment by hadley** [comment]
@evanmiller I think adding similar support for stata would be very useful as well. I think what I'll probably do is allow users to opt-in to a data structure where each column gets an additional "missing" attribute that's T/F for SPSS, and a character for SAS/Stata.

I'm assuming there's no way to easily see if a column uses any tagged missing values apart from iterating over every value.

**Comment by evanmiller** [comment]
Haven't touched that bit of code in a few months but IIRC Stata tagged values are implemented in ReadStat. You are correct that there is no way to know a priori if tagged values are used. The most common tag is "no tag" so just be aware of that when designing the haven API.
