### ISSUE TITLE
Feature request: Add a way of specifying output formats

### ISSUE THREAD

**Issue by gorcha** [hadley/haven#119]
When writing a .sav file, numeric variables use F8.2 as their format, and string variables default to the length of the longest string in the field.

It would be great to be able to specify variable format, possibly by passing an optional named vector to write_sav.

**Comment by evanmiller** [comment]
If someone wants to tackle this, haven just needs to pass the format string as the penultimate argument to `readstat_add_variable`, i.e. replace `NULL` in these lines:

https://github.com/hadley/haven/blob/274ae7016a2b6b114401beab6c3ece9ca5fc4746/src/DfWriter.cpp#L161
https://github.com/hadley/haven/blob/274ae7016a2b6b114401beab6c3ece9ca5fc4746/src/DfWriter.cpp#L177
https://github.com/hadley/haven/blob/274ae7016a2b6b114401beab6c3ece9ca5fc4746/src/DfWriter.cpp#L200

**Comment by gorcha** [comment]
I didn't realise that was all that needed to be modified - happy to have a crack at it!

Thanks
