### ISSUE TITLE
write_dta() incorrectly interprets NA values

### ISSUE THREAD

**Issue by woodape** [hadley/haven#127]
Hi, thanks for the work on the package, this kind of functionality is very needed and the effort to bring it to R is very appreciated. I have two bugs, but will put them in separate issues:

I'm using Arch Linux, Stata 12,  R version 3.2.2, and haven version 0.2.0.9000

When loading in a Stata dta file, read_dta() correctly interprets missing data as "NA" values, but when writing this object back into a dta file with write_dta(), it translates "NA" values into the number 9.21436484e+18. 

Do the following in Stata:

    set obs 100
    gen rand = runiform()
    replace rand = . if rand < .5
    save test1

Then in R:

    library(haven)
    library(foreign)
    # Read in with haven
    D <- read_dta("test1.dta") # Missing values are NA
    rand <- runif(100)
    E <- data.frame(rand=ifelse(rand < .5 , NA , rand))
    # Write with haven
    write_dta(D,path="test1-1.dta")
    write_dta(E,path="test1-2.dta")
    # Write with foreign
    write.dta(D,file="test1-3.dta")

Then again in Stata:

    clear all
    * Use the haven written dataset
    use test1-1
    list
    * NA values have been converted to 9.21436484e+18
    clear
    use test1-2
    list
    * NA values have been converted to 9.21436484e+18
    clear
    * Use the foreign written dataset
    use test1-3
    list
    * NA values have been converted to missing values

I had the same problem when trying to read in a Stata 14 dta file from someone else, but I can't test because I only have Stata 12.

**Comment by woodape** [comment]
This problem seems to be persisting, but with different numbers. I find NA values being written as 2147483621

This is when I've read in a Stata14 file with read_dta() and wrote it back as a Stata file with write_dta()

**Comment by woodape** [comment]
A little more testing

    > library(haven)
    > library(foreign)

    > DD<-read_dta("ag.dta")    # Seems to read in just fine, but I'm not sure as I don't have Stata14
     # With foreign
    > write.dta(DD,"ag2.dta")
    Error in write.dta(DD, "ag2.dta") : 
      empty string is not valid in Stata's documented format
    In addition: Warning message:
    In write.dta(DD, "ag2.dta") :
      character strings of >244 bytes in column 52 will be truncated
     # With haven
    > write_dta(DD,path="ag3.dta")    # Changes NA values to 2147483621

**Comment by yimingli** [comment]
Same problem here. In my case, some NAs were replaced by 9.21436484e+18, and others 2147483621.

```r
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lazyeval_0.1.10  testthat_0.11.0  magrittr_1.5     statar_0.3.0     dplyr_0.4.3      data.table_1.9.6
[7] haven_0.2.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2        munsell_0.4.2      colorspace_1.2-6   R6_2.1.1           stringr_1.0.0     
 [6] plyr_1.8.3         tools_3.2.2        parallel_3.2.2     grid_3.2.2         gtable_0.1.2      
[11] DBI_0.3.1          stargazer_5.2      matrixStats_0.50.1 digest_0.6.8       assertthat_0.1    
[16] crayon_1.3.1       ggplot2_2.0.0      tidyr_0.3.1        memoise_0.2.1      stringi_1.0-1     
[21] scales_0.3.0       chron_2.3-47       proto_0.3-10
```
