### ISSUE TITLE
read_dta() interprets negative numbers as NA

### ISSUE THREAD

**Issue by woodape** [hadley/haven#128]
Hi, second issue encountered - but compounds the other issue - #127 . Again, thanks for the work on the package.

I'm using Arch Linux, Stata 12, R version 3.2.2, and haven version 0.2.0.9000

When loading in a Stata dta file, read_dta() interprets negative numbers as "NA" values.

Do the following in Stata:

    set obs 100
    gen rand = runiform()*2 - 1
    save test2

Then in R:

    library(haven)
    library(foreign)
    # Read in with haven
    D <- read_dta("test2.dta") # Negative values are NA
    # Read in with foreign
    E <- read.dta("test2.dta")  # Negative values are correct

This one is a bit more difficult to deal with than #127 as all the data is lost in the translation.

**Comment by evanmiller** [comment]
Thanks -- this issue and #127 are now fixed in ReadStat/master; someone just needs to get the sources updated in Haven.

**Comment by woodape** [comment]
Thanks for the reply, I'm glad to hear that there is a clear solution to both issues. From the commit history here and at WizardMac/ReadStat it looks like you have been doing the most recent updates related to ReadStat issues, would you be able to update the sources?

**Comment by evanmiller** [comment]
Ok pull request opened: #129

**Comment by woodape** [comment]
Fantastic, thanks!
