### ISSUE TITLE
problem with CHAR compressed SAS datasets

### ISSUE THREAD

**Issue by reikoch** [hadley/haven#131]
Not all char compressed SAS datasets can be read; possibly when a certain size is exceeded.

An example dataset with 16 MB random generated data you find as "bar.sas7bdat" in [https://github.com/reikoch/testfiles].

read_sas refuses to read it with the message
> read_sas('~/xx/bar.sas7bdat')
> Error: Failed to parse /opt/BIOSTAT/home/kochr4/xx/bar.sas7bdat: Invalid file, or file has unsupported features.

Subsets of this file work fine.

**Comment by evanmiller** [comment]
Is it row subsets or column subsets that work fine?

**Comment by evanmiller** [comment]
By the way this is a ReadStat issue so please re-file over here:

https://github.com/WizardMac/ReadStat/issues

Thanks!

**Comment by hadley** [comment]
Closing since this is mostly a readstat issue.
