### ISSUE TITLE
Odd issue with "hms" class

### ISSUE THREAD

**Issue by danhalligan** [hadley/haven#136]
If I have a list `dat` containing a vector of class "hms", I cannot coerce the list to a data.frame.

For example, going from a data.frame -> list and back again should work OK, but throws an error:

    > class(df)
    [1] "data.frame"

    > sapply(df, class)
              C1           C2           C3 
     "character" "data.frame"        "hms" 

    > as.data.frame(as.list(df))
    Error in as.data.frame.default(x[[i]], optional = TRUE) : 
      cannot coerce class ""hms"" to a data.frame

    > as.data.frame(as.list(df[, -3]))
    # run OK.

**Comment by hadley** [comment]
Will be fixed in new version of hms (which will soon power haven).

@krlmlr do you think you could do a hms release in the next couple of weeks?

**Comment by krlmlr** [comment]
hms is on CRAN, but negative and >24h times are currently only in the dev version. I can take a look at #162 soon.
