### ISSUE TITLE
Value labels are missing 

### ISSUE THREAD

**Issue by drkamarul** [hadley/haven#137]
can read well stata data with 
foreign::read.dta('datamssm.dta')

though received 

Warning messages:
1: In read.dta("datamssm.dta") :
  value labels ('yesno') for 'tgidf' are missing
2: In read.dta("datamssm.dta") :
  value labels ('yesno') for 'hdlidf' are missing

BUT with 
haven::read_dta("datamssm.dta")
all variables become 'atomic' and 

I received this error

summary(dataMet)
Error: `x` and `labels` must be same type

**Comment by hadley** [comment]
Duplicate of #86
