### ISSUE TITLE
write_dta: dates are off by 10 years

### ISSUE THREAD

**Issue by diogocp** [hadley/haven#139]
Example:
```
df <- data.frame(date = as.Date("2015-11-30"))
write_dta(df, "date-test.dta")
```
When I open date-test.dta in Stata, the variable has the value 16769. After I apply the %td format, Stata shows it as 29nov2005.

Interestingly, `read_dta` is working correctly. Reading that same file back into R gives me the date 2005-11-29 (as long as I save it in Stata after `format %td`, otherwise it is read as a double).

Stata stores dates as "days since 01jan1960 (01jan1960 = 0)".

**Comment by diogocp** [comment]
I don't know much about Rcpp, but I think the problem is here: https://github.com/hadley/haven/blob/8f65dbc289a30cfd651bf5b201700d4ed1d15cdc/src/DfWriter.cpp#L50

Dates go into that branch and are coerced to numeric using the R epoch. They need to be handled separately. Unfortunately, there is no specific SEXPTYPE for Dates.

Any ideas?

**Comment by hadley** [comment]
Done in 944466bdaeb804359930364e3d8bfcc41329c841
