### ISSUE TITLE
Still trying to get past issue 101

### ISSUE THREAD

**Issue by nunsuch123** [hadley/haven#142]
Hello and thank you in advance for your help. Issue 101 was closed and I have attempted to use the github version rather than cran but cannot get past the following:
Error in get(method, envir = home) : 
  lazy-load database '/Users/lintagliata/Library/R/3.2/library/haven/R/haven.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘haven’

This either happens directly at the installation or when I try to load the package.

**Comment by nunsuch123** [comment]
using RStudio v0.99.465 OS X

**Comment by nunsuch123** [comment]
7th attempt seemed to do it after may retries and attempts to update readstat. readstat couldn't be updated due to errors, but when I restarted R again to try an 8th time, my dataset was readable. Not sure why all the trouble, but please feel free to close.

**Comment by diogocp** [comment]
You can close and reopen your own issues.
