### ISSUE TITLE
write_dta should use the smallest possible integral type

### ISSUE THREAD

**Issue by diogocp** [hadley/haven#143]
Currently all `integer` and `logical` vectors are written as `READSTAT_TYPE_INT32` (Stata's `long`). Stata has two smaller integral types: `byte` and `int` (16 bits). The memory savings from using smaller types can be quite significant when working with large datasets.

write_dta should write all `logical` vectors as `byte` variables, and select the most efficient type for `integer` vectors (by calculating the max and min value).

**Comment by hadley** [comment]
Readstat doesn't currently support the byte type, and in general, I think it's a bad idea to automatically pick the variable type based on the range of the value, as it can lead to confusing behaviour when the values of the variable change.

**Comment by evanmiller** [comment]
For the record, ReadStat does support a byte (char) type (`READSTAT_TYPE_CHAR`).
