### ISSUE TITLE
Error:  Failed to parse (read_sas)

### ISSUE THREAD

**Issue by davidjones-spartan** [hadley/haven#147]
I get the following error when reading larger SAS files:

 Error: Failed to parse /home/rstudio/Novartis/ITP/physician_dim.sas7bdat: Invalid file, or file has unsupported features.

I have 14 SAS compressed files.  All files larger than 27,000KB give me the error.  Only one smaller gives me the error (24KB).  Please help!

Thanks,
Dave
davidjones.fineart@gmail.com

**Comment by evanmiller** [comment]
Hi Dave,

Can you share the SAS file that's not opening? Also what version of haven are you running?

**Comment by davidjones-spartan** [comment]
Evan,
Thanks for you help!  I'm using whatever version is the latest that would
install with the install command.

Attached is a small file that won't open.  It's also a .GZ file, is that
OK?  Please don't share this file, it is a proprietary client file.

Can you please let me know that you received this email and file?

Thanks,
Dave

**Comment by davidjones-spartan** [comment]
Haven version 0.2.0

**Comment by evanmiller** [comment]
Hi,

I didn't get the file, please email it to me directly. emmiller@gmail.com

Also you should try installing the development version of haven:

    devtools::install_github("hadley/haven")

**Comment by evanmiller** [comment]
Looking at the file, it appears to be the same problem described here: https://github.com/WizardMac/ReadStat/issues/42

**Comment by davidjones-spartan** [comment]
Ok, thanks.  What is the solution for someone who doesn't have SAS?

**Comment by davidjones-spartan** [comment]
What's also interesting is that haven worked on 6 of the 14 files.  The 14
files are all from the same vendor and are part of a package.  The 14 files
are part of the same data set constructed around a specific market.  The
source data behind the 14 files is the same.  I would think they would all
have identical formatting.

**Comment by marcobiagetti** [comment]
I got the same problem: read_sas reads 4 out of 5 sas7bdat files in my wd but gets me the same error as David's above (for the first file in my list.files to be more precise).

**Comment by benjamin-chan** [comment]
I'm getting the `Failed to parse <...>: Invalid file, or file has unsupported features.` message with `haven_0.2.0.9000`. 

The `.sas7bdat` file is binary compressed and has 6144 observations and 5357 variables.

Reproducible example:

```
library(haven)
root <- "https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/AcuteInpatientPPS/Downloads"
url <- file.path(root, "FY2016-CMS-1632-FR-HCRIS.zip")
f <- tempfile()
download.file(url, f, mode="wb")
files <- unzip(f, list=TRUE)
files
dataFile <- grep("sas7bdat$", files$Name, value=TRUE)
dataFile
unzip(f, files=dataFile)
D <- read_sas(f)
sessionInfo()
```

Session info:

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_0.2.0.9000    RevoUtilsMath_3.2.2

loaded via a namespace (and not attached):
 [1] magrittr_1.5    IRdisplay_0.3   tools_3.2.2     base64enc_0.1-3
 [5] Rcpp_0.12.1     uuid_0.1-2      stringi_0.5-5   rzmq_0.7.7     
 [9] IRkernel_0.5    jsonlite_0.9.16 stringr_1.0.0   digest_0.6.8   
[13] repr_0.4        evaluate_0.7.2 
```

**Comment by davidjones-spartan** [comment]
Sorry to say that R can't read compressed SAS files yet.  I had to use another software to convert the compressed SAS file into an uncompressed SAS file, then was able to read into R.

**Comment by benjamin-chan** [comment]
Ack. I noticed this is related to issue as https://github.com/hadley/haven/issues/131. I would recommend merging with #131.
