### ISSUE TITLE
Can't install haven development version

### ISSUE THREAD

**Issue by dbcuervo** [hadley/haven#148]
I need to read some Stata 14 files into R and am trying to use the development version of "haven".  When I run the code "devtools::install_github("hadley/haven"), the package fails to compile and I get this message:  

"
*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="haven.dll" OBJECTS="CKHashTable.o DfReader.o DfWriter.o RcppExports.o readstat_bits.o readstat_convert.o readstat_dta.o readstat_dta_read.o readstat_dta_write.o readstat_error.o readstat_io.o readstat_parser.o readstat_por.o readstat_por_parse.o readstat_sas.o readstat_sas_catalog.o readstat_sas_data.o readstat_sav.o readstat_sav_parse.o readstat_sav_read.o readstat_sav_write.o readstat_spss.o readstat_spss_parse.o readstat_value.o readstat_variable.o readstat_writer.o"' had status 127
ERROR: compilation failed for package 'haven'
* removing 'C:/Users/David/Documents/R/win-library/3.2/haven'
* restoring previous 'C:/Users/David/Documents/R/win-library/3.2/haven'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\David\Documents\R\win-library\3.2\00LOCK-hadley-haven-11fb5f5\haven\libs\x64\haven.dll to C:\Users\David\Documents\R\win-library\3.2\haven\libs\x64\haven.dll: Permission denied
Error: Command failed (1)" 

I'd be grateful for any help you could provide.  

Thanks,
David

**Comment by amilymoor** [comment]
Exactly the same problem here. Can anyone help us here?

Thanks,
Tong

**Comment by amilymoor** [comment]
Ok, as I spent some time researching over it, I think the major problem is because your R is not the most recent version. as haven is now built under R 3.2.4, I guess the developer version needs the same R version as well.

I updated my R, Rtools, devtools, and re-run install_github again. Everything works out fine now.

Tong

**Comment by hadley** [comment]
You'll sometimes see the "Permission denied Error" on windows if you already have haven loaded. I'd recommend trying again in a clean R session.
