### ISSUE TITLE
write_dta() incorrectly write "-Inf" resulting from log(0)

### ISSUE THREAD

**Issue by yimingli** [hadley/haven#149]
`write_dta` seems to have some problems writing `-Inf` as missing values in Stata file.

```r
library(foreign)
library(readstata13)
library(haven)
library(dplyr)

df = data.frame(var = c(0, 1:99))
df = df %>% mutate(log_var = log(var))

df %>% write_dta("/tmp/log_zero_haven.dta")
df %>% write.dta("/tmp/log_zero_foreign.dta")
df %>% save.dta13("/tmp/log_zero_readstata13.dta")
```

Here are the Stata results: only `foreign` package does it right.

```stata
. use "/tmp/log_zero_haven.dta", clear

. sum

Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
    var |       100        49.5    29.01149          0         99
log_var |       100           .           .          -    4.59512

. 
. use "/tmp/log_zero_foreign.dta", clear
(Written by R.              )

. sum

Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
    var |       100        49.5    29.01149          0         99
log_var |        99    3.627618     .927587          0    4.59512

. 
. use "/tmp/log_zero_readstata13.dta", clear
(Written by R)

. sum

Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
    var |       100        49.5    29.01149          0         99
log_var |       100           .           .          -    4.59512
```

**Comment by hadley** [comment]
But -Inf isn't a missing value? Or does stata not support inf?

**Comment by yimingli** [comment]
Stata does not support Inf. Stata uses a little dot `.` to denote missing values, but as is shown above -Inf is stored as a hyphen. I've never seen this before. But it caused problem in later regression analysis, which took me a while to trace back to this inf issue.

Here is an example when I take logarithm in Stata.

```
. set obs 100
obs was 0, now 100

. gen var = _n -1

. gen log_var = log(var)
(1 missing value generated)

. list in 1/6, clean

       var    log_var  
  1.     0          .  
  2.     1          0  
  3.     2   .6931472  
  4.     3   1.098612  
  5.     4   1.386294  
  6.     5   1.609438  

. sum

    Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
         var |       100        49.5    29.01149          0         99
     log_var |        99    3.627618     .927587          0    4.59512
```

**Comment by yimingli** [comment]
I also created an issue for `readstata13` package here at https://github.com/sjewo/readstata13/issues/25

**Comment by sjewo** [comment]
As far as I understand the dta format specifications does not handle inf values explicitly: +inf will be converted to NA by Stata 14, but -inf becomes a dash. We opted for assigning a NA to -inf, so that inf and -inf will produce the same value in Stata.

**Comment by bachl** [comment]
I can confirm a similar problem for write_sav(). NA in the R data seems to result in some kind of Inf value that SPSS cannot deal with in most procedures.

**Comment by hadley** [comment]
@evanmiller is this haven's responsibility or readstats? Inf is a valid floating point value.

**Comment by evanmiller** [comment]
Tough to say. The DTA spec is silent on infinite values, but clearly Stata doesn't expect them. If we regard DTA as an "open" transport format then I see no reason to flatten them.

I suppose ReadStat could offer an opt-in write_positive_infinity API, but that seems a bit much.

**Comment by hadley** [comment]
Ok, I'll fix/hack around on my end then
