### ISSUE TITLE
parso Java library (not an issue)

### ISSUE THREAD

**Issue by harrysouthworth** [hadley/haven#15]
In case it's helpful...

Matt Shotwell has a package on github called sas7bdat.parso. It's a wrapper for the GGA Software Parso Java library (ask Google).

I've used Parso to read many dozens of .sas7bdat files without problems (well, the only problem I've found is unescaped quotes in their csv writer - but that's the csv writer, not the sas7bdat reader). I know someone who is working on having Parso turn a bunch of SAS datasets directly into a SQLite db to avoid the whole csv nonsense.

For info, Parso was written because they couldn't get Sassy Reader to do what they wanted. Sassy Reader was based on Matt Shotwells package.

Again, I hope it helps.
Harry

**Comment by hadley** [comment]
Thanks. @evanmiller are you aware of this?

**Comment by evanmiller** [comment]
I had heard of it. But given the licensing (GPLv3 / commercial), I won't touch it with a ten-foot pole.
