### ISSUE TITLE
Possible memory leak in write_sav

### ISSUE THREAD

**Issue by njanetos** [hadley/haven#152]
When I try to save a data frame with many long strings to .sav format, it crashes. (First reported at leeper/rio#85.) 

For example, if I run

```
library(haven)

d = data.frame(x = rep(0, 2000))
for (i in 1:length(d)) {
    d[i] = "This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length. This is a test string of some length."
}

haven::write_sav(d, "test.sav")
```
R crashes with
```
$ Rscript test.R
*** Error in `/usr/lib/R/bin/exec/R': free(): corrupted unsorted chunks: 0x0000000002311e00 ***
Aborted (core dumped)
```
This happens on Ubuntu running R 3.2.2.

**Comment by evanmiller** [comment]
This should fix the crash (at the expense of truncating string values > 255 chars):

https://github.com/WizardMac/ReadStat/commit/1ab480a56356c9d64b82159ba73eb74a4d5f211c

**Comment by njanetos** [comment]
Is this related to WizardMac/ReadStat#45? I'm unfamiliar with SPSS and STATA, but surprised that they are unable to support 256 characters.

**Comment by evanmiller** [comment]
They are both ancient formats that added support for long variables late in life. The issues are related inasmuch as both exporters will require non-trivial coding to support their respective long-variable storage mechanisms.

**Comment by njanetos** [comment]
I see, how disturbing. I have one more question -- where can I find documentation on how SPSS stores long strings?

By the way, thank you so much for writing this library and for taking the time to address this.

**Comment by evanmiller** [comment]
See

https://www.gnu.org/software/pspp/pspp-dev/html_node/Very-Long-String-Record.html#Very-Long-String-Record
