### ISSUE TITLE
haven does not support SPSS new compressed format file (zsav)

### ISSUE THREAD

**Issue by TUFFERST** [hadley/haven#153]
While trying to read a zsav file, we have the following message : 
_Failed to parse C:\Users\...\Test.zsav: Invalid file, or file has unsupported features_
Is it planned to extend abilities of haven to be able to read zsav SPSS file?
Thanks

**Comment by hadley** [comment]
@evanmiller can you comment please?

**Comment by evanmiller** [comment]
I haven't investigated the format too much. The docs mention that ZSAV is always UTF-8, so it's likely that it's not just .sav.gz. Would like to support it, but I don't plan to pursue until there is demand on my end.

**Comment by hadley** [comment]
@TUFFERST not at this time.

**Comment by TUFFERST** [comment]
Hi,

Does your reply mean that you do not plan to extend abilities of haven to be able to read zsav SPSS file?

Thanks,

Best regards,

Stéphane Tufféry

De : Hadley Wickham [mailto:notifications@github.com]
Envoyé : lundi 30 mai 2016 15:55
À : hadley/haven <haven@noreply.github.com>
Cc : TUFFÉRY Stéphane <stephane.tuffery@e-i.com>; Mention <mention@noreply.github.com>
Objet : Re: [hadley/haven] haven does not support SPSS new compressed format file (zsav) (#153)


Closed #153<https://github.com/hadley/haven/issues/153>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/hadley/haven/issues/153#event-676072308>, or mute the thread<https://github.com/notifications/unsubscribe/ARO_6MzDd8QewWveAQVqK7SWvj5IS32fks5qGuwggaJpZM4H4w5w>.
***********************************************************************************************
Ce message et toutes les pièces jointes sont confidentiels et établis à l'intention exclusive 
de son ou ses destinataires. Si vous avez reçu ce message par erreur, merci d'en avertir
immédiatement l'émetteur et de détruire le message. Toute modification, édition, utilisation ou
diffusion non autorisée est interdite. L'émetteur décline toute responsabilité au titre de ce
message s'il a été modifié, déformé, falsifié, infecté par un virus ou encore édité ou diffusé
sans autorisation.


***********************************************************************************************
This message and any attachments are confidential and intended for the named addressee(s) only.
If you have received this message in error, please notify immediately the sender, then delete
the message. Any unauthorized modification, edition, use or dissemination is prohibited.
The sender shall not be liable for this message if it has been modified, altered, falsified, infected
by a virus or even edited or disseminated without authorization.
***********************************************************************************************

**Comment by jimhester** [comment]
`zsav` seems to be simply a gzip compressed `sav` file. So you should be able to open it without any code changes by simply using `base::gzfile()` in combination with `haven::read_sav()`. For example

``` r
url <- "https://bitbucket.org/fomcl/savreaderwriter/raw/537f5bd0257abcea9fe52e2134730bbbebd96d4a/savReaderWriter/test_data/zlib_compressed.zsav"

# download file and to disk, then open with gzfile
download.file(url, basename(url))
data <- haven::read_sav(gzfile(basename(url)))
data
#> # A tibble: 2 x 4
#>    var1  var2  var3      bdate
#>   <chr> <dbl> <dbl>      <chr>
#> 1 Test1     1     1 2010-08-11
#> 2 Test2     2     1 1910-01-12

# You can even read the file directly using `curl::curl()` and `gzcon()`.
data2 <- haven::read_sav(gzcon(curl::curl(url)))
data2
#> # A tibble: 2 x 4
#>    var1  var2  var3      bdate
#>   <chr> <dbl> <dbl>      <chr>
#> 1 Test1     1     1 2010-08-11
#> 2 Test2     2     1 1910-01-12
```

**Comment by evanmiller** [comment]
@jimhester I don't think ZSAV is simply .sav.gz; see the PSPP documentation on Zlib compression here: https://www.gnu.org/software/pspp/pspp-dev/html_node/Data-Record.html#Data-Record

Relevant discussion here: http://pspp-users.gnu.narkive.com/IToYTzIz/zsav-format-support-zcompressed-subcommand
