### ISSUE TITLE
error parsing stata 14 file

### ISSUE THREAD

**Issue by huashan** [hadley/haven#158]
Hi,

I encountered a problem when trying to open the following demo data. It's a stata version 14 file with UTF-8 encoded labels. haven reports message below:

Error: Failed to parse demo.dta: Invalid file, or file has unsupported features.

[demo.zip](https://github.com/hadley/haven/files/234569/demo.zip)

Thanks.

**Comment by evanmiller** [comment]
FYI this file opens with the latest version of ReadStat. The issue could be an older version of haven, or an out-of-date ReadStat used in haven.

**Comment by huashan** [comment]
thanks @evanmiller .

Solved by upgrading from 0.2.0 to 0.2.0.9000.
