### ISSUE TITLE
Stata (before 13) needs optional encoding parameter

### ISSUE THREAD

**Issue by huashan** [hadley/haven#163]
If a version 13 dta file with labels defined with non UTF-8 encoding, the 0.2.0.9000 version fails to recognize variable labels.

I think these lines should be commented out in `readstat_dta.c`, or should `read_dta()` have one more parameter for assigning default encoding?

    if (ds_format < 118) {
        ctx->converter = iconv_open("UTF-8", "WINDOWS-1252");
    }

**Comment by evanmiller** [comment]
Hi,

What encoding do your labels use?

**Comment by huashan** [comment]
@evanmiller 
Thanks for the reply. The encoding is GB2312. I also test a version 14 dta file, same result as above.
With those three lines commented out, I could use `Encoding(x)<-` in R to set the correct encoding for var labels.

**Comment by evanmiller** [comment]
@hadley I've extended the C API to allow manual specification of the file encoding. The trouble is that pre-14 Stata uses the system encoding (usually Win 1252) but does not indicate what that encoding is anywhere in the file. For kicks I also allow specifying the output encoding, which defaults to UTF-8. Here's the API diff from https://github.com/WizardMac/ReadStat/commit/c4e0d488e57f4e572fbc96d1527ee1e435134f7c:

```{c}
// Usually inferred from the file, but sometimes a manual override is desirable.
// In particular, pre-14 Stata uses the system encoding, which is usually Win 1252
// but could be anything. `encoding' should be an iconv-compatible name.
readstat_error_t readstat_set_input_character_encoding(readstat_parser_t *parser, const char *encoding);

// Defaults to UTF-8. Pass in NULL to disable transliteration.
readstat_error_t readstat_set_output_character_encoding(readstat_parser_t *parser, const char *encoding);
```

**Comment by hadley** [comment]
@evanmiller is it safe to default this to UTF-8? Or does stata 14 use different types of encoding and I need to respect the type used for the file?

**Comment by hadley** [comment]
@evanmiller assumed it probably should only be set when the user specifically wants an override.
