### ISSUE TITLE
Correct way to navigate to path?

### ISSUE THREAD

**Issue by joshash** [hadley/haven#165]
Such a trivial issue, but why is this path not working?

`read_dta(/Users/ashkij/Desktop/varcons.dta)` yields error `unexpected '/' in "read_dta(/"` 

And `read_dta(Users/ashkij/Desktop/varcons.dta)` yields an error `Error in clean_path(path) : object 'Users' not found`

What would be the correct way to navigate to the STATA file?

**Comment by tklebel** [comment]
You need to specify the path by wrapping it in ```""```:

```R
read_dta("/Users/ashkij/Desktop/varcons.dta")
```
