### ISSUE TITLE
labelled-class causes errors in some other packages

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#168]
I'm not sure how to best address this issue, but some packages, like the **effects**-packages, don't like the `labelled`-class-attribute.

```
library(haven)
library(effects)

y <- sample(1:10, size = 50, replace = T)
x1 <- labelled(as.numeric(sample(1:3, size = 50, replace = T)), c(lo = 1, mid = 2, hi = 3))
x2 <- labelled(as.numeric(sample(1:4, size = 50, replace = T)), c(`total disagree` = 1, `disagree` = 2, `agree` = 3, `total agree` = 4))

fit <- lm(y ~ x1 + x2)

# Does not work!
allEffects(fit)
```
> Fehler in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels

After removing the labelled-class-attribute, everything works as intended.

```
x1 <- unclass(x1)
x2 <- unclass(x2)

allEffects(fit)
```

**Comment by hadley** [comment]
I shouldn't imagine that labelled vectors would work with any arbitrary package. My assumption is that if you want to work with them in R you'll need to turn them into factors.

**Comment by sjPlot** [comment]
But why do you then need the labelled-class-attribute anyway? There's no need in losing information (i.e. dropping attributes after conversion to factor). You could leave the imported data as numeric or atomic, and simply add the attributes (like **foreign** does). Many packages (e.g. stats::lm or lme4::lmer etc., and your packages) simply copy these attributes, and other packages may then facilitate these information.

I know, this is more a design-question, and I'm not expecting or intending to open a broad discussion here. ;-)

**Comment by hadley** [comment]
The labelled calls _is_ just some extra attributes on top of a atomic vector. But failing to mark this as a special class is asking for trouble in the long-run.
