### ISSUE TITLE
haven::write_sav can crash

### ISSUE THREAD

**Issue by rubenarslan** [hadley/haven#171]
Are you already interested in crash reports? I'm not sure, I just eagerly installed from the master branch to test the date and label writing to .sav. 
If not, ignore this and sorry 😅 

Writing the following data results in a crash on my platform 1 out of 3 times. If I use all the data and not just a tiny slice, it always crashes.
I'm not sure how to report details about crashes. R quits with a fatal error and Rstudio reloads, I don't get a message. If I turn `debug` on the function Rstudio crashes too and I can see from the Mac OS X reporting tools that it's a segfault, but I'm not sure whether that's now related to haven or RStudio.

```
widgets = structure(list(time_period = structure(NA_integer_, .Label = c("quaternary", 
	"neogene", "paleogene", "cretaceous", "jurassic", "triassic", 
	"permian", "carboniferous", "devonian", "silurian", "ordovician", 
	"cambrian"), class = "factor"), partner = NA_integer_), .Names = c("time_period", 
	"partner"), row.names = 1L, class = "data.frame")
haven::write_sav(widgets, "w.sav")
```

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

Oh, also, this is more minor: when installing via devtools, it complained about missing build tools. Solution was to go to 3.3.0, so I was a bit confused by that (I had all build tools).

**Comment by evanmiller** [comment]
This is a bug in ReadStat... working on a fix.

**Comment by evanmiller** [comment]
Fixed in https://github.com/WizardMac/ReadStat/commit/8d5e263a3dae7c0628dfb5aacff8c8bec56deed7.

Note that to get the fix, haven will need to be updated to work with changed ReadStat APIs.

**Comment by rubenarslan** [comment]
Works like a charm (ie reads and writes nicely, reproduces item and value
labels).

Except SPSS does not open the files anymore ^^.
For the mtcars write_sav example the error in SPSS V20
yields is #1405 in column 8.
And it says something it's an invalid file.
Hadley Wickham <notifications@github.com> schrieb am Do., 2. Juni 2016 um
17:38:

**Comment by evanmiller** [comment]
I don't have access to SPSS so I can't test directly. Can you please try two small examples using value labels:

* One where all string values (not necessarily labels) are EXACTLY the same length -- and longer than 8 characters

* One where at least one string value has a different length from the others -- and at least one string value has a length longer than 8 characters

Make sure that value labels are being used in both cases. Thanks.

**Comment by rubenarslan** [comment]
I can do that but maybe I wasn't clear, I think this has nothing to do with
value labels, the write_sav example writes the all numeric mtcars dataset
and stilll crashes.
I did not update readstat manually on my local, should I have?
Do you still want me to try your suggestion?

>

**Comment by evanmiller** [comment]
@rubenarslan Ah OK I did not understand the full context. There is no need to try the suggestion then.

I am not sure what's going on -- it's possible some of the newer bits for defining the measure are causing a parse error. Please open a new issue.
