### ISSUE TITLE
as_factor drops unused labels when levels = "default".

### ISSUE THREAD

**Issue by itsdalmo** [hadley/haven#172]
As title states, `as_factor.labelled` drops unused labels when `levels = "default"` (or "both").

Example:
```r
  s1 <- labelled(rep(1, 3), c("A" = 1, "B" = 2, "C" = 3))
  exp <- factor(rep("A", 3), levels = c("A", "B", "C"))
  str(as_factor(s1, levels = "default"))
  # Factor w/ 1 level "A": 1 1 1
```

Maybe this is intended, but I'd like to propose that the default should include all labels to safely (and easily) convert labelled variables to factors without information-loss. Users can instead explicitly call `droplevels()` after converting to produce the result above.

-Kristian

**Comment by hadley** [comment]
Can you give an example of where this causes a problem with a realistic labelled example?

**Comment by itsdalmo** [comment]
Started writing this in the pullrequest:

@hadley - My main concern is that there is no option to `levels` which preserves all information when converting a labelled vector to a factor - I.e., you either lose the labels, or you lose the values that are not labelled:

```R
labs <- setNames(1:3, c("A", "B"))
labelled <- labelled(c(1, 3), labels = labs)

as_factor(labelled, levels = "default") # Drops B and C from levels
as_factor(labelled, levels = "labels") # 3 becomes NA
```

However, I see what you mean with your likert example,`as.integer()` on the results would give the wrong values. But perhaps this should only apply when `typeof(x) == "integer"` (or numeric). For character vectors, I think it is better to preserve the order in which the labels were specified in the data, than to sort them alphabetically:

```R
s1 <- labelled(c("N", "A", "D"), c(Agree = "A", Neutral = "N", Disagree = "D"))
as_factor(s1)
#> [1] Neutral  Agree    Disagree
#> Levels: Agree Disagree Neutral
```

E.g., in the example above I think it makes more sense if the outcome is Agree, Neutral, Disagree. And I think this is the best solution in general when the underlying type is `"character"`.

**Comment by itsdalmo** [comment]
To answer your question about a realistic labelled example:
Since the issue outlined here is the default behavior for `as_factor`, I think it's fairly easy to imagine a dataset from a small/medium-sized survey where none of the respondents have ticked a particular label. 

```R
s1 <- labelled(c("N", "A", "D"), c(Agree = "A", Neutral = "N", Disagree = "D", `Don't know` = "U"))
as_factor(s1) # "Don't know" is dropped.
```

In my opinion, it makes more sense to leave the unused labels in there - and have users call `droplevels()` after if they'd like only the labels that have actually been used. As it is now, if you convert the labelled vector to factor you'd have to go back to the original source to see what options the respondents didn't pick. 

(`levels = "labels"` is an option, but requires that the data is neat and has labels for each value. And the only way to ensure this for users, is to make a table of the values and compare that to the labels you see when printing the variable.)

**Comment by itsdalmo** [comment]
(Made two posts earlier, merged them into this.)

#### Original issue

`labelled` contains all the labels and values, but none of the `levels` options for `as_factor` can be used to convert to `factor` in a reliable way. Since the assumption is that users will want to *"coerce to a standard R class soon after importing"*, I think it's important that they don't lose any information along the way:

```R
labs <- setNames(1:3, c("A", "B"))
labelled <- labelled(c(1, 3), labels = labs)

as_factor(labelled, levels = "default") # Drops B and C from levels
as_factor(labelled, levels = "labels")  # 3 becomes NA
```



#### Realistic example

I think it's fairly common for survey data to have implicit missing values on one or more items. In the example below, users would lose the implicit missing values when converting to factor. 

```R
labs <- setNames(1:6, c("Strongly Agree", "Agree", "Neutral", "Disagree", "Strongly disagree", "Don't know"))
labelled <- labelled(sample(1:5, size = 100, replace = TRUE), labels = labs)

as_factor(labelled, levels = "default") # Drops "Strongly disagree" and "Don't know"
```

Using `levels = "labels"` is fine if you can assume that that all variables have correct labels, if not then users will have to:
- Figure out (i.e. manually inspect) whether any labels are missing for valid responses.
- Add missing labels to the `labelled` vector before converting to factor (not supported out of the box). 

#### Fix

It's just a matter of always keeping all the labels when converting to factor. In response to what wrote in the pull rquest, I'd also like to suggest that `as_factor` prefers the order in which the labels are specified if `typeof(x) == "character"`, instead of the alphabetically sorted values as in this example:

```R
set.seed(84)
vals <- c("Strongly Agree", "Agree", "Neutral", "Disagree", "Strongly disagree", "Don't know")
labelled <- labelled(sample(vals, size = 100, replace = TRUE), labels = setNames(vals, vals))

as_factor(labelled, levels = "default")
#> ...
#> Levels: Agree Disagree Don't know Neutral Strongly Agree Strongly disagree
```

In the above, I think it makes more sense to just keep the order of the labels for values that have labels, and just add the (sorted) values without labels to the end of the factor levels.

#### Code

```R
  # Inside as_factor.labelled
  levels <- match.arg(levels)
  labels <- attr(x, "labels")

  if (levels == "default" || levels == "both") {
    if (levels == "both") {
      names(labels) <- paste0("[", labels, "] ", names(labels))
    }

    # Replace each value with its label
    levs <- replace_with(sort(unique(x)), unname(labels), names(labels))

    # Retain all labels (and their order for labelled character vectors) (#172)
    if (typeof(x) == "character") {
      levs <- unique(c(names(labels)), levs)
    } else {
      levs <- unique(c(levs, names(labels)))
    }

    x <- replace_with(x, unname(labels), names(labels))

    factor(x, levels = levs, ordered = ordered)
  } else {
    # Hidden
  }
```

**Comment by itsdalmo** [comment]
@hadley: 
You are right, the order of labels for is not something the user control in SPSS (not sure about Stata/SAS). I'm guessing the order for labels after importing would be alphabetical to begin with, so it would only be helpful after using the `labelled()` constructor (where order can be specified).

**Comment by larmarange** [comment]
In some way, this discussion highlights a more general topic regarding labelled vectors. As far as I understood it, we can distinct two different approaches/philosophy.

The first one, adopted by `haven`, is to consider that labelled class is just an intermediate format for data import from SAS/Stata/SPSS. Therefore, there is no need to provide too many functions for labelled vectors manipulation, the main purpose being to convert to more "standard" R formats. In such approach, functions need to remain simple with not too much options.

A second approach is to consider that labelled vectors are also useful for data manipulation, data cleaning and data recoding, in particular for scientists used to work with survey data, in a study team where over scientists are working with other software, and/or when the purpose is to re-export to SAS/Stata/SPSS. In such situation, it is appropriate to have several functions to manipulate labelled vectors. However, this is probably not the purpose of the `haven` package. This is why the `labelled` has been developed. 

In some way, these two approaches are not antagonist, but complementary.

@itsdalmo if you need to control the order of the factor that is produced, in particular to keep the order of the labels, you could have a look to function `to_factor` in `labelled` package. Being able to control the order of labels was also one of my need. In `labelled` package, you have several option to define how to sort them. However, this sort of function is probably relevant only for the second approach, not the first one.

**Comment by itsdalmo** [comment]
Thanks for the tip @larmarange!

However, I don't think my needs warrant another import/dependency as I really only need to be able to convert labelled vectors to factors in a safe and reliable manner. And I think that `levels = "default"` not dropping unused labels would do just that.

@hadley was correct about my second point (at least for SPSS); there is no way to create an equivalent to the code below in SPSS. I.e., SPSS sorts labels according to value and we'd end up with Female as the first label when reading the vector from .sav, or when opening it in SPSS.

```R
labelled(c("M", "F"), labels = c("Male" = "M", "Female" = "F"))
```

But I think the original issue is valid. If we are meant to convert away from `labelled` soon after importing, we need to feel safe doing so without manually checking for missing labels. After removing the `if` statement in my pull request, `as_factor` keeps all existing labels and values that are missing labels.

Since the updated PR keeps the sorting for character vectors also, this means that we can't `as_factor(labelled(...))` a character vector in R and expect labels to have levels in the order specified, but users should probably just be creating the factor directly anyhow. 

I think this makes `as_factor` safer to use/better overall.
