### ISSUE TITLE
robustify read_dta() for reading in stata 13 and 14 

### ISSUE THREAD

**Issue by statsccpr** [hadley/haven#181]
For this exact reason, I'm averse to proprietary stats software formats. Unfortunately many colleagues use stata etc.

# UPDATE
Using githubs dev version of 'haven::read_dta(file=foo)'
works for my particular scenario. I've tried three different stata formats

# Old Details Below

This can probably be Labeled as an 'enhancement'

There are some instances where haven::read_dta() errors out when reading a .dta dataset output from stata 13 and 14.

I'm not even sure how to provide a reproducible example. Should i email the .dta dataset to whoever's interested?

```
haven::read_dta(path='/u/project/foo.dta')
Error: Failed to parse /u/project/foo.dta: Invalid file, or file has unsupported features.
```

However, when using an alternative r package for this same data, say 'readstata13' 
https://github.com/sjewo/readstata13

```
readstata13::read.dta13(file='/u/project/foo.dta')
```

works perfectly fine

```
  ___  ____  ____  ____  ____ (R)
 /__    /   ____/   /   ____/
___/   /   /___/   /   /___/   14.1   Copyright 1985-2015 StataCorp LP
  Statistics/Data Analysis            StataCorp
                                      4905 Lakeway Drive
     Special Edition                  College Station, Texas 77845 USA
                                      800-STATA-PC        http://www.stata.com
                                      979-696-4600        stata@stata.com
                                      979-696-4601 (fax)
```

Here's some r code

```
# using stata 14.1 SE 'save as' different formats
# reading via haven::read_dta

# doesn't work with haven
file_path1 = 'Z:/projects/rec_link_pow_dora/data/test_haven/test_dta.dta'
# works with all
file_path2 = 'Z:/projects/rec_link_pow_dora/data/test_haven/test_dta13.dta'
# works with all
file_path3 = 'Z:/projects/rec_link_pow_dora/data/test_haven/test_dta1211.dta'


# install.packages('haven')  # cran version
test = haven::read_dta(path=file_path1)
test = haven::read_dta(path=file_path2)
test = haven::read_dta(path=file_path3)

head(test)
str(test)

# install.packages('readstata13')  # cran version
# readstata13::read.dta13() works with al
test = readstata13::read.dta13(file=file_path1)
test = readstata13::read.dta13(file=file_path2)
test = readstata13::read.dta13(file=file_path3)

head(test)
str(test)

# works with github dev version
devtools::install_github("hadley/haven")  # github dev version
test = haven::read_dta(file=file_path1)
test = haven::read_dta(file=file_path2)
test = haven::read_dta(file=file_path3)

```

**Comment by evanmiller** [comment]
Hi,

Feel free to post a Dropbox link or email me directly with the DTA file: emmiller@gmail.com

**Comment by hadley** [comment]
@statsccpr also, are you using the dev version or the cran version?  If you're using the CRAN version, it's possible the problem has already been fixed in the dev version.

**Comment by statsccpr** [comment]
@hadley was right, for my particular scenario, the dev version via devtools::install_github("hadley/haven") works for all 3 dta formats output by stata 14.1
