### ISSUE TITLE
Accessing labelled tagged NAs

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#182]
I'm very impressed by the new `NA` mechanism of haven, especially the tagged NA is a brilliant feature. For some functions of my package, I need to know which labelled NA corresponds to which NA tag:

```
x <- c(1:3, tagged_na("a", "c", "z"), 3:1)
y <- labelled(x, c("First" = tagged_na("c"), "Refused" = tagged_na("a"), "Not home" = tagged_na("z")))
str(y)
```

> Class 'labelled'  atomic [1:9] 1 2 3 NA NA NA 3 2 1
>   ..- attr(*, "labels")= Named num [1:3] NA NA NA
>   .. ..- attr(*, "names")= chr [1:3] "First" "Refused" "Not home"

```
format_tagged_na(y)
```

> [1] "    1" "    2" "    3" "NA(a)" "NA(c)" "NA(z)" "    3" "    2" "    1"

So, how do I know wich labels - `attr(y, "labels")` returns 3 times `NA` - correspons to NA(a), NA(c) and NA(z)? (I don't mean the print-methods, which gives me the information, but how to access this information if you need it for a package function and don't want to print). Is there a method I have missed? If not, could you a method that could do this?

**Comment by hadley** [comment]
`na_tag()` ?

**Comment by sjPlot** [comment]
`na_tag()` returns all NA values in order of appearance in the vector:

    na_tag(y)

> [1] NA  NA  NA  "a" "c" "z" NA  NA  NA 

What I would like to have:
If a functions gets a labelled vector, how can I find out which NA-labels are associated with which tagged NA value?

`na_tag` gives me "a", "c" and "z". `attr(*, "labels")` gives me three names NA-values, with the labels for the NA values as names. How do I know that the first name, _First_, is associated with the NA-value `NA(c)`?

Am I missing something here?

I can imagine something like `na_info` or `na_labels`, which could return the `attr(*, "labels")`, but replace the three NA-values with the related `na_tags` or so.

**Comment by sjPlot** [comment]
So, expected output could probably be:

```
na_labels(y)
   First  Refused Not home 
   NA(c)    NA(a)    NA(z) 
```

**Comment by hadley** [comment]
You need to use `na_tag()` on the `attr(x, "labels")` too.

**Comment by sjPlot** [comment]
Ah, so easy! Thanks!
