### ISSUE TITLE
A Stata-like `codebook` function that quickly summarises a variable

### ISSUE THREAD

**Issue by LaDilettante** [hadley/haven#183]
`codebook` is a Stata function that gives a quick overview of a variable (its name, missingness, range, value, labels). (See image). Stata users frequently ask for this function when they switch to R.

![stata_codebook](https://cloud.githubusercontent.com/assets/4418241/15945884/60c1f2cc-2e62-11e6-8460-6b4e0fc8f2a1.png)

Is this something `haven` wants to implement with regards to its `labelled` class?
- Argument for: With `codebook`, `haven` would attract even more Stata users & teams.
- Argument against: `labelled` is a temporary class to be converted into `factor`.

Happy to contribute PR if you think it's a good idea.

**Comment by hadley** [comment]
It feels like it's out of scope for haven, not only for the reasons you mentioned, but also because it's useful for non-labelled variables.  I'm not sure where a good home would be. Tibble maybe?

But maybe it deserves it's own package? You could imagine it being an htmlwidget that generated nicely formatted output (plus graphics?)

**Comment by larmarange** [comment]
You could have a look to describe function in questionr package.

**Comment by LaDilettante** [comment]
@larmarange Thanks for the tip. Unfortunately the package author does not have much information on how to contribute. Plus, this idea is more general than just survey.

@hadley I'll open an issue on and contribute to Tibble.

**Comment by larmarange** [comment]
@LaDilettante sorry didn't really understand your comment about contribution in `questionr`. That package is on GitHub : https://github.com/juba/questionr So it's easy to discuss and to propose issues or pull requests to the authors

**Comment by sjPlot** [comment]
So what are exactly the requested information for the output? Maybe I can implement such a function in [sjPlot](https://github.com/sjPlot/devel), as one of this package's focus lies on facilitating labelled data.
