### ISSUE TITLE
as.data.frame.matrix coercion of read_spss result can leave each column as its own `tbl`

### ISSUE THREAD

**Issue by ajdamico** [hadley/haven#184]
hi, i'm not sure if this `as.data.frame.matrix` behavior is expected?  it is new as of version `0.2.0.9000` ..sorry if i'm missing something and thank you!

	# # # # running the same script with haven version 0.2.0 on CRAN:
	sapply(y,class)[1:5]
	 # IDSCHOOL   IDCNTRY  ACBGLOWG  ACBGHIGG  ACBGTENR 
	# "numeric" "numeric" "numeric" "numeric" "numeric" 

	# using version 0.2.0.9000
	devtools::install_github("hadley/haven")

	library(haven)

	# # # # # # # # start of download/import of big file
	tf <- tempfile()

	download.file( "http://timss.bc.edu/timss2003i/PDF/t03_spss_1.zip" , tf , mode = 'wb' )

	z <- unzip( tf , exdir = tempdir() )

	w <- grep( "ACGAUSm3" , z , value = TRUE )
	# # # # # # # # end of download/import

	x <- read_spss( w )

	sapply(x,class)[1:5]
	  # IDSCHOOL    IDCNTRY   ACBGLOWG   ACBGHIGG   ACBGTENR 
	 # "numeric"  "numeric" "labelled" "labelled"  "numeric" 

	y <- as.data.frame.matrix(x)
	 
	sapply(y,class)[,1:5]
		 # IDSCHOOL     IDCNTRY      ACBGLOWG     ACBGHIGG     ACBGTENR    
	# [1,] "tbl_df"     "tbl_df"     "tbl_df"     "tbl_df"     "tbl_df"    
	# [2,] "tbl"        "tbl"        "tbl"        "tbl"        "tbl"       
	# [3,] "data.frame" "data.frame" "data.frame" "data.frame" "data.frame"
	 
	z <- as.data.frame(x)
	 
	sapply(z,class)[1:5]
	  # IDSCHOOL    IDCNTRY   ACBGLOWG   ACBGHIGG   ACBGTENR 
	 # "numeric"  "numeric" "labelled" "labelled"  "numeric" 

	 
	# after as.data.frame.matrix runs, a single column is still all three classes:
	class(as.data.frame.matrix(x)[,1])
	# [1] "tbl_df"     "tbl"        "data.frame"

	# zapping labels does prevent the issue, though
	as.data.frame.matrix(sapply(x,zap_labels))[,1]
	  # [1]    1    4    6    7    8    9   11   12   13   15   16   18   20   21   22   23   24   25   26   27   29   30   32   33   34   36   38   39   40   41   42   43   44   45   46   48   49   51
	 # [39]   52   53   55   56   58   59   60   62   63   64   65   66   67   69   70   72   73   76   77   78   79   80   81   82   83   84   85   86   87   89   91   92   93   94   95   96   97   98
	 # [77]  101  102  103  104  105  106  107  109  111  112  114  115  116  117  118  119  120  121  122  123  126  127  128  129  131  132  134  135  136  137  138  139  140  141  142  143  144  146
	# [115]  147  148  150  153  155  156  157  158  159  160  161  162  165  168  169  172  173  174  175  176  178  179  180  181  182  183  185  186  187  188  189  190  191  192  193  195  196  197
	# [153]  199  200  202  203  204  206  207  208  209  211  213  214  215  216  217  218  219  220  221  222  224  225  226  227  228  230 1017 1037 1050 1054 1057 1071 1074 1075 1088 1125 1149 1151
	# [191] 1152 1163 1166 1167 1210 1212 1229 2002 2005 2031 2035 2108 2130 2164

**Comment by hadley** [comment]
I have absolutely no idea why you would expect `as.data.frame.matrix` to do something useful here
