### ISSUE TITLE
Is it possible to have a `add_val_labels()` function for pipeline?

### ISSUE THREAD

**Issue by jjchern** [hadley/haven#185]
Right now if one wants to add value labels for a variable, it would be something like the following:

```R
df = tibble::data_frame(s1 = c("M", "M", "F"), s2 = c(1, 1, 2))
df$s1 = haven::labelled(df$s1, c(Male = "M", Female = "F"))
df$s2 = haven::labelled(df$s2, c(Male = 1, Female = 2))
```

I was wondering if there can be a function `add_val_lables()` so that one can do

```R
df %>%
    add_val_labels(s1, c(Male = "M", Female = "F")) %>%
    add_val_labels(s2, c(Male = 1, Female = 2)) 
``` 

Or

```R
df %>%
    add_val_labels(s1, s1 == "M" ~ "Male", s1 == "F" ~ "Female") %>%
    add_val_labels(s2, s2 == 1 ~ "Male", s2 == 2 ~ "Female") 
```

**Comment by larmarange** [comment]
did you have a look at labelled package? https://cran.r-project.org/web/packages/labelled/

**Comment by jjchern** [comment]
Thank you for the comment! I just read `labelled`'s vignette, and it seems that I can do the following:

```R
labelled::val_labels(df) = list(
        s1 = c(Male = "M", Female = "F"), 
        s2 = c(Male = 1, Female = 2)
)
```

This is close to what I need. Still, maybe a function for pipeline could be worthwhile.

**Comment by larmarange** [comment]
In dev version of labelled, I just added a `add_value_labels` function compatible with `%>%`. Please note that the syntax is slightly different from your proposal:

```r
if (require(dplyr)) {
   df <- data_frame(s1 = c("M", "M", "F"), s2 = c(1, 1, 2))
   df <- df %>% add_val_labels(s1 = c(Male = "M", Female = "F"), s2 = c(Yes = 1, No = 2))
   val_labels(df)
}
```

It still need some tests, as well as similar functions for variable labels.

**Comment by jjchern** [comment]
Oh, that's very nice. Thank you for the quick response! I will close this issue then.
