### ISSUE TITLE
Is it possible for `haven` to import dataset attributes from Stata? 

### ISSUE THREAD

**Issue by jjchern** [hadley/haven#186]
# Background

Stata has various dataset attributes, such as 
- dataset label, 
- last saved date, 
- short notes that allow dataset maintainer to include other metadata: data source, sample, maintainer email, etc.

Take the dataset `nlsw88` for example. Once loaded, it prints out a short dataset label:

![webuse](https://cloud.githubusercontent.com/assets/11262574/16166753/b62c7dc0-34b3-11e6-9656-4c9ba32f5af0.png)

The next thing a typical Stata user would do is probably use the `describe` command to get a basic idea about the dataset. As shown in the following screenshot, the `d` command print out a header that shows data label, last saved date, and indicates that there're more notes about this dataset.

![describe](https://cloud.githubusercontent.com/assets/11262574/16166955/85d915b4-34b5-11e6-8889-fe875137ece2.png)

The `notes` command can then prints out these notes:

![notes](https://cloud.githubusercontent.com/assets/11262574/16166957/88b08542-34b5-11e6-9915-490742987071.png)

The `codebook, header` command shows similar dataset attributes:

![cb-header](https://cloud.githubusercontent.com/assets/11262574/16166967/9953c116-34b5-11e6-99aa-be9a7d61d081.png)

# Feature Request

Right now `haven` is not preserving these dataset level attributes. I was wondering if it's possible to keep them, as it's done in the `foreign` package:

```R
foreign::read.dta("http://www.stata-press.com/data/r12/nlsw88.dta") %>% str()
#> 'data.frame': 2246 obs. of  17 variables:
#> ...
#> - attr(*, "datalabel")= chr "NLSW, 1988 extract"
#> - attr(*, "time.stamp")= chr "1 May 2011 22:52"
#> - attr(*, "formats")= chr  "%8.0g" "%8.0g" "%8.0g" "%8.0g" ...
#> - attr(*, "types")= int  252 251 251 251 251 251 251 251 251 251 ...
#> - attr(*, "val.labels")= chr  "" "" "racelbl" "marlbl" ...
#> - attr(*, "var.labels")= chr  "NLS id" "age in current year" "race" "married" ...
#> - attr(*, "expansion.fields")=List of 7
#> ..$ : chr  "_dta" "note1" "1988 data, extracted from National Longitudinal of Young Woman"
#> ..$ : chr  "_dta" "note2" "who were ages 14-24 in 1968 (NLSW)."
#> ..$ : chr  "_dta" "note3" "This dataset is the result of extraction and processing by various"
#> ..$ : chr  "_dta" "note4" "people at various times."
#> ..$ : chr  "_dta" "note5" "For more information on the NLS, see"
#> ..$ : chr  "_dta" "note0" "6"
#> ..$ : chr  "_dta" "note6" "http://www.bls.gov/nls/"
#> - attr(*, "version")= int 12
```

`foreign` is not doing quite correctly for keeping "format", "types", "val.labels", and "var.labels" as these attributes belong to corresponding variables, but I believe it'd be worthwhile to keep others at the dataset level.

Moreover, it might also be useful for `tibble` to print out some of these attributes, and indicate that there're more detailed notes.

Probably related: [hadley/tibble#90](https://github.com/hadley/tibble/issues/90)

**Comment by evanmiller** [comment]
@hadley The ReadStat build is currently broken, but I've added a new "metadata handler" that reports the file label, timestamp, and format version. Looks like there are some `strftime` portability issues though so don't integrate just yet.

**Comment by evanmiller** [comment]
Okay, I've fixed the `strftime` issues. Should be ready to integrate, although I don't have a solution yet for Stata's "notes" feature.

**Comment by hadley** [comment]
@jjchern could you please create a simple stata file that I can include in haven and use for testing?

**Comment by jjchern** [comment]
@hadley Sure. How about the `iris` dataset? Here's the same dataset in three Stata versions. Just in case. 

```R
urls = paste0("http://www.stata-press.com/data/r", 12:14, "/iris.dta")
fils = paste0("iris_v", 12:14, ".dta")
purrr::map2(urls, fils, ~ if(!file.exists(.y)) download.file(.x, .y))
list.files(pattern = "iris_")
#> [1] "iris_v12.dta" "iris_v13.dta" "iris_v14.dta"
```

And here's a screenshot that shows the dataset attributes:

![screen shot 2016-07-29 at 9 59 04 am](https://cloud.githubusercontent.com/assets/11262574/17254292/c5cf32cc-5579-11e6-812f-23465b6bfaf4.png)

**Comment by hadley** [comment]
Can you make your own really simple dataset? I want to include it in haven for testing

**Comment by jjchern** [comment]
Sorry about that. Here's a test dataset:

[test_metadata.dta.zip](https://github.com/hadley/haven/files/391219/test_metadata.dta.zip)

The Stata code that generates the dataset (just for the record):

```Stata
clear
set seed 13
set obs 5
gen id = _n
gen female = runiform() < .6
gen treatment = runiform() < .5
gen outcome = 1 + 2 * treatment + (rnormal() < .5)
label data "This is a test dataset."
notes: Reference: https://github.com/hadley/haven/issues/186
saveold "~/Desktop/test_metadata.dta", replace v(12)
```

And a screenshot of how the metadata looks like in Stata's output window:

![screen shot 2016-07-29 at 2 31 04 pm](https://cloud.githubusercontent.com/assets/11262574/17261261/7627d4c4-559a-11e6-87d1-e57f642a0182.png)

As always, thanks a lot for the attention.

**Comment by evanmiller** [comment]
Just to provide a quick update on the ReadStat side of things, I am working on adding read/write support for Stata notes, as well as the SPSS document record. You can track the progress of that effort over here:

https://github.com/WizardMac/ReadStat/issues/73

**Comment by hadley** [comment]
@evanmiller when I load that "notes.dta" I get two notes: one is "1" and the other is "Reference: ...". Is that what you expect?

**Comment by evanmiller** [comment]
That is what I see in the data file.

The "1" note is labeled "notes0" internally (handler receives note_index=0), so maybe it has some private meaning, e.g. number of notes or first note index. This stuff is completely undocumented so I'm flying a little blind.

**Comment by hadley** [comment]
@evanmiller also I get an "invalid timestamp" for http://www.stata-press.com/data/r12/nlsw88.dta

**Comment by hadley** [comment]
Looking at the notes in http://www.stata-press.com/data/r14/iris.dta, I'm guess that "empty" notes are given a default value based on their position.

**Comment by evanmiller** [comment]
@hadley I'll open an issue on the invalid timestamp issue.

If you come to a better understanding about notes and how ReadStat should handle empty ones please file an issue.
