### ISSUE TITLE
read-functions do not encode to UTF-8

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#187]
I have attached a small SPSS-file, where column names with German umlauts are not correctly encoded.

The current column names:
```
test <- haven::read_spss("Test1.sav")
colnames(test)
> [1] "Ã„quivalenzeinkommen"
```

Required output:
```
Encoding(colnames(test)) <- "UTF-8"
colnames(test)
> [1] "Äquivalenzeinkommen"
```

Value and variable labels, however, are correctly imported:
```
attr(test[[1]], "labels")
>       äquivalent nicht äquivalent 
>                1                2 
```

[Test1.zip](https://github.com/hadley/haven/files/325404/Test1.zip)

**Comment by hadley** [comment]
Have you tried with dev haven?

**Comment by sjPlot** [comment]
Yes. To be sure,I just re-installed and tested with the current GitHub snapshot.

**Comment by sjPlot** [comment]
> > sessionInfo()
> R version 3.3.0 (2016-05-03)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows 7 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
> [5] LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] haven_0.2.0.9000
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.5        lattice_0.20-33    codetools_0.2-14   mvtnorm_1.0-5      zoo_1.7-13         assertthat_0.1     MASS_7.3-45       
>  [8] grid_3.3.0         plyr_1.8.4         xtable_1.8-2       nlme_3.1-127       coda_0.18-1        estimability_1.1-1 lsmeans_2.23      
> [15] multcomp_1.4-5     minqa_1.2.4        nloptr_1.0.4       Matrix_1.2-6       sandwich_2.3-4     splines_3.3.0      TH.data_1.0-7     
> [22] lme4_1.1-12        tools_3.3.0        parallel_3.3.0     pbkrtest_0.4-6     survival_2.39-2    tibble_1.0        
>

**Comment by evanmiller** [comment]
This example file works OK for me.

```R
> devtools::install_github("hadley/haven")
> test <- haven::read_spss("/Users/emiller/Downloads/Test1.sav")
> colnames(test)
[1] "Äquivalenzeinkommen"
```

**Comment by Ohlsen** [comment]
I get the same problematic result. I had that on other occasions as well, it seems to be a problem with windows and R when they don´t use the same locale.

**Comment by tklebel** [comment]
I have no problems on Mac with German/Austrian locale: 

```r

test <- haven::read_spss("Downloads/Test1.sav")
> colnames(test)
[1] "Äquivalenzeinkommen"
> 
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.1220)         
 language (EN)                        
 collate  de_AT.UTF-8                 
 tz       Europe/Vienna               
 date     2016-06-22                  

Packages ---------------------------------------------------------------------------------------------------
 package    * version     date       source                        
 assertthat   0.1         2013-12-06 CRAN (R 3.3.0)                
 devtools     1.11.1.9000 2016-06-21 github (hadley/devtools)      
 digest       0.6.9       2016-01-08 CRAN (R 3.3.0)                
 haven        0.2.0.9000  2016-06-21 github (hadley/haven)         
 memoise      1.0.0       2016-01-29 CRAN (R 3.3.0)                
 Rcpp         0.12.5      2016-05-14 CRAN (R 3.3.0)                
 readr        0.2.2.9000  2016-06-07 Github (hadley/readr@8b253b2) 
 rstudioapi   0.5         2016-01-24 CRAN (R 3.3.0)                
 tibble       1.0-10      2016-06-21 Github (hadley/tibble@ed1b068)
 withr        1.0.1       2016-02-04 CRAN (R 3.3.0)  
```

**Comment by sjPlot** [comment]
Strange. In my [sjmisc-package](https://github.com/sjPlot/sjmisc), where I wrap the `read_spss`-function, I have added an `enc` argument, which - if specified - simply changes the encoding of column name (see [here](https://github.com/sjPlot/sjmisc/blob/master/R/read_write.R#L67)). I'm afraid this is not the fastest solution, or if it works for other encodings/locales as well, but it works at least. ;-)

**Comment by hadley** [comment]
This is only a problem on Windows. Will be a simple fix when I'm next working on haven.
