### ISSUE TITLE
Reading old stata binary file takes lots of RAM and never finishes

### ISSUE THREAD

**Issue by crsh** [hadley/haven#189]
Hi,

I'm having trouble with an old `.dta` file (I don't know how old it is). I have tried reading it with `foreign::read.dta`, which tells me it's "not a Stata version 5-12 .dta file." `readstata13::read.dta13` didn't work either ("First byte: Not a dta-file we can read."). When I tried `haven::read_dta` the process drew ~10 GB of RAM and didn't seem to finish (the Stata file is only 1.5 MB).

If the file is pre-Stata 5, which it might be, I'm not sure whether it is outside of `haven`'s scope, but I think throwing an error would be preferable to the current behavior of `haven::read_dta`. I could send you the file via e-mail if you are interested.

**Comment by evanmiller** [comment]
Strange. If you can pass the file along to me I will take a look. Thanks!
