### ISSUE TITLE
Test "print_tagged_na is stable"

### ISSUE THREAD

**Issue by larmarange** [hadley/haven#190]
The test `expect_output_file(print_tagged_na(x), "tagged-na.txt")` is failing if the option `width` is not equal to 80 (could be be the case according to your local configuration).

Would it be appropriate to add the command `options(width = 80)` in that test? (https://github.com/hadley/haven/blob/master/tests/testthat/test-tagged_na.R#L57)

**Comment by hadley** [comment]
Would be better to pass width argument to print

**Comment by larmarange** [comment]
It seems that the default print method used for characters doesn't take into account a `width` argument.

Example:

```
x <- c(1:100, tagged_na(letters), NA)
print(format_tagged_na(x), width = 20, quote = FALSE)
```

The width argument will not be taken into account.

**Comment by hadley** [comment]
I've decided this should actually be fixed in testthat: https://github.com/hadley/testthat/issues/514
