### ISSUE TITLE
Password protected SAS files

### ISSUE THREAD

**Issue by akitepowell** [hadley/haven#191]
Is there a way to read in password protected SAS files using haven?  I don't see it anywhere in the documentation, but I'm also somewhat new to this.  If not, that would be helpful functionality to add if possible.

**Comment by hadley** [comment]
Probably not, but @evanmiller can comment on the difficult of adding to readstat.

**Comment by evanmiller** [comment]
I am not sure what's involved in password protection. (I.e. whether the password encrypts the file or it's just an honor system with the reading software.)

**Comment by BioStatMatt** [comment]
If it's honor system, and password simply another header field, then it seems existing routines should work with password protected files. I know that encryption is an option, whether as part of password protection or separate.
