### ISSUE TITLE
`write_sav` issues with labelled class vectors

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#193]
I have found some issues when saving labelled data to SPSS. I used the latest dev-build from 25th June. First, here is the reproducible example for the issues:

```
library(haven)
x <- labelled(c(1:3, tagged_na("a", "c", "z"), 4:1),
              c("Agreement" = 1, "äquivalent" = 2, "Disagreement" = 4, "First" = tagged_na("c"),
                "Refused" = tagged_na("a"), "Not home" = tagged_na("z")))

attr(x, "label") <- "Äquivalenzeinkommen"
x
# test.sav
haven::write_sav(data.frame(test = x), "test.sav")
# test2.sav
haven::write_sav(data.frame(test = haven::as_factor(x)), "test2.sav")
```

Now to what I have found:

  * Using the `data.frame` method on a labelled vector produces a column name with dots at the end. Dots are no legal characters at the end of variable names in SPSS. Trying to run any command with this variable leads to an error in SPSS.

```
> data.frame(x)
   x..i..
1       1
2       2
3       3
4      NA
```

![spss_2](https://cloud.githubusercontent.com/assets/4901179/16392000/03b9cca2-3caa-11e6-80c4-598decd00be9.png)

  * It seems that the "tags" of tagged NA values are saved, but recognized as invalid value labels. See screenshot and also the screenshot above:

![spss_1](https://cloud.githubusercontent.com/assets/4901179/16391961/d43502da-3ca9-11e6-9a6a-cc3e6cf98c70.png)

  * After changing the variable name, the value labels are not correctly assigned. See screenshot above, where 1 is agreement, 2 is äquivalenz and 4 is disagreement. Running the frequency command in SPSS gives following:

![spss_4](https://cloud.githubusercontent.com/assets/4901179/16392104/7392d636-3caa-11e6-8fc7-bbe873039111.png)

  * After editing some of the value labels, assignment still is not correct:

![spss_5](https://cloud.githubusercontent.com/assets/4901179/16392117/855cab9e-3caa-11e6-9ef1-97c1ad5741ee.png)

To summarise, `labelled` vectors are not properly saved to SPSS. **However**, _factors_ are. The second SPSS file, where I used `haven::as_factor(x))`, seems to work, except that `as_factor` does not convert values to NA (thus, they are counted as regular values).

  * Correct value labels

![spss_try2_2](https://cloud.githubusercontent.com/assets/4901179/16392167/d2f9e16e-3caa-11e6-81d3-2d1b3a096b2b.png)

  * Correct frequencies

![spss_try2_1](https://cloud.githubusercontent.com/assets/4901179/16392181/db125458-3caa-11e6-9e5f-b9de21dec84d.png)

  1. I would suggest to convert any labelled vector to factor with `as_factor` before writing the data.
  2. Furthermore, it would be nice to include an option, where (tagged/labelled) NA values can be converted to NA. You have to be sure to convert them to regular NA (i.e. removing the "tag" from the NA value), else you have broken value labels (see 1st/2nd screenshot at top)

[Test1 and 2.zip](https://github.com/hadley/haven/files/335621/Test1.and.2.zip)

**Comment by hadley** [comment]
It would be helpful if you could file multiple issues for different problems. I've fixed the first one.

I'm not currently planning to add full write support for tagged missing values at this time.

**Comment by sjPlot** [comment]
No, I was not thinking about full write support for tagged NAs, but for converting them to regular NA before writing, because tagged NA produce invalid values in the output file.

**Comment by hadley** [comment]
In that case, please file a minimal bug report along those lines.
