### ISSUE TITLE
Encoding column names error ?

### ISSUE THREAD

**Issue by skanskan** [hadley/haven#195]
Hello.

I have a file that can be read properly in Stata but when imported to R with my <- read_dta("area7.dta")  doesn't read the column names properly, it produces some strange symbols.
I've tried with the option encoding="UTF-8"  but it's not accepted.

**Comment by hadley** [comment]
Did you install haven from github?

**Comment by skanskan** [comment]
I've just updated and it works, I don't know if the problem was solved or I changed anything.
Regards
