### ISSUE TITLE
sapply(mydataframe, class)

### ISSUE THREAD

**Issue by skanskan** [hadley/haven#196]
I don't know why if I do a
sapply(mydataframe, class)
I get a vector with the class of every column in the data.frame

But if I do the same with the data.frame that haven creates when I import an SPSS file  then the result is not the same, it's a list instead.

**Comment by hadley** [comment]
That's the reason you shouldn't use `sapply()` - see http://r4ds.had.co.nz/robust-code.html#unpredictable-types
