### ISSUE TITLE
sas7bdat file working on dev but not CRAN version, even though CRAN version number ahead of dev?

### ISSUE THREAD

**Issue by ajdamico** [hadley/haven#199]
sorry if i'm being an idiot.  i was excited to see haven 0.2.1 had been pushed to CRAN, but it looks like a file that worked using the dev version isn't yet working on the CRAN version?  thanks hadley!

	# data preparation
	downloader::source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/master/Download%20Cache/download%20cache.R" , prompt = FALSE , echo = FALSE )
	tf1 <- tempfile()
	download_cached( "http://www.census.gov/housing/extract_files/data%20extracts/cpsasec14/hhld.sas7bdat" , tf1 , mode = 'wb' )

	
	# CRAN says version 0.2.1
	install.packages("haven")		
	library(haven)
	
	# fails
	w <- read_sas(tf1)

	# https://github.com/hadley/haven/blob/master/DESCRIPTION says version 0.2.0.9000
	devtools::install_github("hadley/haven")
	library(haven)
	
	# works
	w <- read_sas(tf1)

**Comment by hadley** [comment]
That was just a point release to fix a failing check. The next realise of this branch will be 1.0.0
