### ISSUE TITLE
Compatibility of label attributes to foreign-package

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#20]
Is there a specific reason why label attributes in Haven have other names than attributes from foreign-package? Would be easier for other packages that access value and variable labels to have the same attribute names.

**Comment by hadley** [comment]
Yes, because I think creating a new class is a better approach than adding a large number of arguments to each read function.

**Comment by sjPlot** [comment]
But does creating a new class interfere with using the same attribute names ("value.labels" instead of "labels")

**Comment by hadley** [comment]
No, it shouldn't

**Comment by sjPlot** [comment]
So why not use the same attribute names? ;-)
Background of my question is, if it becomes a more common way to set (variable and value) label attributes to vectors, more and more function could read these labels for plotting / printing instead of using the vector name (column name) itself. Thus, it would be helpful to have a "standard" of naming value and variable attributes - at least this would make life easier for package developers, for instance when my functions look for these attributes and I don't have to take care how these attributes are named.

**Comment by hadley** [comment]
I think the way that foreign does variable labels is fundamentally wrong - variable labels are a property of the variable, not of the data frame. And I don't want to guarantee precise foreign compatibility because it makes a lot of extra work for me, and I don't think it saves a lot of time for other people.

**Comment by sjPlot** [comment]
I agree that Variable labels should be an Attribute of the variables itself, not the data frame - that's why my read_spss function attaches these labels to each variable after reading the spss file. My only concern is just the name of the attribute: "value.labels" instead of "label" and variable.label instead of label.

**Comment by hadley** [comment]
I'd be happy to review a pull request that made this change
