### ISSUE TITLE
v0.2.1 fails to read SAS datasets

### ISSUE THREAD

**Issue by reikoch** [hadley/haven#200]
Hi Hadley,
the new branch and tag v0.2.1 fails to read a couple of SAS files the master branch can read, for instance [https://github.com/reikoch/testfiles/blob/master/bar.sas7bdat](url). Further, the function read_sas() misses the "encoding" parameter to overrule missing or wrongly stated dataset encodings.

Would it be possible to put a better version of haven onto CRAN?

Kind regards
Reinhold

**Comment by hadley** [comment]
0.2.1 was just a point release to fix some R CMD check issues
