### ISSUE TITLE
Stata 14.1 files won't import

### ISSUE THREAD

**Issue by aghaynes** [hadley/haven#202]
I'm having issues reading stata 14.1 files into R using haven...

Stata:

`
sysuse auto
save "autos"
`

and then in R 

`
dat <- haven::read_dta("temporary/autos.dta")
Error: Failed to parse [...]autos.dta: Invalid file, or file has unsupported features.
`

Is there a known bug at the moment? (I tried to install the github version but the Rcpp version it refers to doesnt appear to be available for haven/the combination of my R version and haven...)

devtools::install_github("hadley/haven")
Downloading GitHub repo hadley/haven@master
from URL https://api.github.com/repos/hadley/haven/zipball/master
Installing haven
Installing 5 packages: curl, hms, lazyeval, Rcpp, tibble
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/curl_1.1.zip'
Content type 'application/zip' length 4418810 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/hms_0.2.zip'
Content type 'application/zip' length 20733 bytes (20 KB)
downloaded 20 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/lazyeval_0.2.0.zip'
Content type 'application/zip' length 138463 bytes (135 KB)
downloaded 135 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/Rcpp_0.12.6.zip'
Content type 'application/zip' length 3221761 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/tibble_1.1.zip'
Content type 'application/zip' length 490853 bytes (479 KB)
downloaded 479 KB

package ‘curl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘curl’
package ‘hms’ successfully unpacked and MD5 sums checked
package ‘lazyeval’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
package ‘tibble’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\haynes\AppData\Local\Temp\Rtmp0S39OQ\downloaded_packages
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL "C:/Users/haynes/AppData/Local/Temp/Rtmp0S39OQ/devtools8d0199a46e2/hadley-haven-96c553f"  \
  --library="C:/Program Files/R/R-3.2.3/library" --install-tests 

ERROR: dependency 'Rcpp' is not available for package 'haven'
* removing 'C:/Program Files/R/R-3.2.3/library/haven'
Error: Command failed (1)

Results of sessionInfo() (after reinstalling haven from CRAN after the unsuccessful github update):
` 
sessionInfo()

R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252   
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] tools_3.2.3 haven_0.2.1 Rcpp_0.12.6
`

**Comment by aghaynes** [comment]
Using the Stata Auto dataset (no need to use one of my own), in Stata :
`
sysuse auto save "auto"
save "auto"
`
and then in R:
`
dat <- haven::read_dta("auto.dta")  
Error: Failed to parse [...]auto.dta: Invalid file, or file has unsupported features.
`

As its a dataset from stata, it shouldn't have any problem (I would have thought)

**Comment by hadley** [comment]
That's not reproducible because I don't have stata...

**Comment by aghaynes** [comment]
the one line code and dataset are here 
https://github.com/aghaynes/misc

**Comment by evanmiller** [comment]
The provided file opens fine with dev haven.

```
> haven::read_dta("/Users/emiller/Downloads/auto.dta")
Source: local data frame [74 x 12]

            make price   mpg rep78 headroom trunk weight length  turn displacement gear_ratio   foreign
           <chr> <dbl> <dbl> <dbl>    <dbl> <dbl>  <dbl>  <dbl> <dbl>        <dbl>      <dbl> <dbl+lbl>
1    AMC Concord  4099    22     3      2.5    11   2930    186    40          121       3.58         0
2      AMC Pacer  4749    17     3      3.0    11   3350    173    40          258       2.53         0
3     AMC Spirit  3799    22    NA      3.0    12   2640    168    35          121       3.08         0
4  Buick Century  4816    20     3      4.5    16   3250    196    40          196       2.93         0
5  Buick Electra  7827    15     4      4.0    20   4080    222    43          350       2.41         0
6  Buick LeSabre  5788    18     3      4.0    21   3670    218    43          231       2.73         0
7     Buick Opel  4453    26    NA      3.0    10   2230    170    34          304       2.87         0
8    Buick Regal  5189    20     3      2.0    16   3280    200    42          196       2.93         0
9  Buick Riviera 10372    16     3      3.5    17   3880    207    43          231       2.93         0
10 Buick Skylark  4082    19     3      3.5    13   3400    200    42          231       3.08         0
..           ...   ...   ...   ...      ...   ...    ...    ...   ...          ...        ...       ...
```
