### ISSUE TITLE
read_sas : wrong labels when importing formats

### ISSUE THREAD

**Issue by the-knife** [hadley/haven#204]
Hello,

When importing SAS dataset with formatted variables, labels and values seem to match correctly only if possible values are given in the good (alphabetical?) order in the _proc format._

Here is a test data generated in SAS :
```
proc format lib=mylib.test_formats ;
 /* both A and B formats are identical, only order of possible values is different*/
 value $A
   "1" = "Male"
   "2" = "Female" ;
 value $B
   "2" = "Female"
   "1" = "Male" ;
run ;

data mylib.test_data ;
   input ID $ SEXA $ SEXB $ ;
   format SEXA $A. SEXB $B. ;
   datalines ;
     ID1 1 1
     ID2 2 2
     ID3 1 1
   ;
run ;
```

The problem arises when importing in R :
```
test_data <- read_sas(
  b7dat = "test_data.sas7bdat", 
  b7cat = "test_formats.sas7bcat")

attr(test_data$SEXA, "labels")
attr(test_data$SEXB, "labels")

test_data$fSEXA <- as_factor(test_data$SEXA)
test_data$fSEXB <- as_factor(test_data$SEXB)

test_data
```
The resulting data.frame is wrong for factor fSEXB :

```
   ID SEXA SEXB  fSEXA  fSEXB
1 ID1    1    1   Male Female
2 ID2    2    2 Female   Male
3 ID3    1    1   Male Female
```

**Comment by hadley** [comment]
I'm pretty sure this is already fixed in the dev version. I could check if you provided a link to the sas files you created.

**Comment by the-knife** [comment]
[test_data](https://github.com/hadley/haven/files/388433/test_data.zip).

**Comment by the-knife** [comment]
[test_data.zip](https://github.com/hadley/haven/files/388446/test_data.zip)

**Comment by hadley** [comment]
Nope, not fixed. I see:

```R
> attr(test_data$SEXA, "labels")
  Male Female   Male Female 
   "1"    "2"    "1"    "2" 
> attr(test_data$SEXB, "labels")
Female   Male 
   "1"    "2" 
```

So it looks like there are two problems there

**Comment by the-knife** [comment]
Thanks for testing.

Note that I don't have the problem with SEXA :
```
> attr(test_data$SEXA, "labels")
  Male Female 
   "1"    "2" 
> attr(test_data$SEXB, "labels")
Female   Male 
   "1"    "2" 
```

**Comment by hadley** [comment]
@evanmiller is this possibly a ReadStat problem? When I debug my `readstat_set_value_label_handler` I get:

```
$A:1 -> Male
$A:2 -> Female
$B:1 -> Female
$B:2 -> Male
$A:1 -> Male
$A:2 -> Female
```

i.e. in `$B` 1 is incorrectly mapped to female, and I see `$A` twice

**Comment by evanmiller** [comment]
The incorrect mapping and double-handling are two separate bugs, will report progress over on the ReadStat issue tracker.

**Comment by evanmiller** [comment]
@the-knife Could you please provide a test file with all four variations? Something like

```
proc format lib=mylib.test_formats ;
 value $A
   "1" = "Male"
   "2" = "Female" ;
 value $B
   "2" = "Female"
   "1" = "Male" ;
 value $C
   "1" = "Female"
   "2" = "Male" ;
 value $B
   "2" = "Male"
   "1" = "Female" ;
run ;
```

**Comment by the-knife** [comment]
@evanmiller 
Sure, I'll do it on Friday (don't have SAS at home).

**Comment by the-knife** [comment]
@evanmiller Here are the sas formats :
[test_formats.zip](https://github.com/hadley/haven/files/415064/test_formats.zip)
(I assumed the last one was $D, not $B)

**Comment by the-knife** [comment]
And here is the [associated data](https://github.com/hadley/haven/files/415100/test_data.zip) generated by the following code : 
```
data mylib.test_data ;
   input ID $ SEXA $ SEXB $ SEXC $ SEXD $ ;
   format SEXA $A. SEXB $B. SEXC $C. SEXD $D.;
   datalines ;
     ID1 1 1 1 1
     ID2 2 2 2 2
     ID3 1 1 1 1
   ;
run ;
```

**Comment by evanmiller** [comment]
Hi, do you experience the same problem with the provided file? In my tests I see

```
Set: $A  Value: 1  Label:  Male
Set: $A  Value: 2  Label:  Female
Set: $B  Value: 2  Label:  Female
Set: $B  Value: 1  Label:  Male
Set: $C  Value: 1  Label:  Female
Set: $C  Value: 2  Label:  Male
Set: $D  Value: 2  Label:  Male
Set: $D  Value: 1  Label:  Female
```

I.e. the expected label order.

**Comment by the-knife** [comment]
Yes, B and D are still reversed.
```
> attr(test_data$SEXA, "labels")
  Male Female 
   "1"    "2" 
> attr(test_data$SEXB, "labels")
Female   Male 
   "1"    "2" 
> attr(test_data$SEXC, "labels")
Female   Male 
   "1"    "2" 
> attr(test_data$SEXD, "labels")
  Male Female 
   "1"    "2" 
```
With the stable haven version, btw. I don't know how to load the dev version.

**Comment by evanmiller** [comment]
With the dev version I see

```{R}
> attr(data$SEXA, "labels")
  Male Female 
   "1"    "2" 
> attr(data$SEXB, "labels")
Female   Male 
   "2"    "1" 
> attr(data$SEXC, "labels")
Female   Male 
   "1"    "2" 
> attr(data$SEXD, "labels")
  Male Female 
   "2"    "1" 
```

Install the dev version with

```{R}
devtools::install_github("hadley/haven")
```

**Comment by the-knife** [comment]
It is working now with the dev version.
Thank you.
