### ISSUE TITLE
as_factor: incorrect labelling for numeric 'labelled' vectors with non-positive values

### ISSUE THREAD

**Issue by mikmart** [hadley/haven#211]
I ran into an issue with missing values appearing in factors when converting `labelled` variables (imported from an SPSS `.sav` file) into `factors` using `as_factor`. It seems conversion from a `labelled` vector to a `factor` using `as_factor` fails when the original `labelled` vector has labels assigned to non-positive values. This seems to be caused by the `match(x, labs)` used in creating the `factor` in `haven:::as_factor.labelled` for non-character vectors.

Here's a sample snippet:
```
> x <- labelled(c(-1, 0, 1), c(A = -1, B = 0, C  = 1))
> x
-1 0 1 
[1] -1  0  1
attr(,"labels")
 A  B  C 
-1  0  1 
> as_factor(x)
[1] C    <NA> <NA>
Levels: A B C
```

(Tested with R version 3.3.1.)

**Comment by hadley** [comment]
This is fixed in the dev version
