### ISSUE TITLE
`droplevels()` removes "label" attribute from a labelled vector

### ISSUE THREAD

**Issue by dchiu911** [hadley/haven#213]
The following code emulates a variable I might get from using `read_sav()`, although here I am adding the `label` attribute afterward.
```{R}
library(dplyr)
likert <- labelled(sample(4, 100, replace = TRUE),
                   c("Strongly Agree" = 1,
                     "Agree" = 2,
                     "Neutral" = 3,
                     "Disagree" = 4,
                     "Strongly Disagree" = 5))
attr(likert, "label") <- "Likert Scale"
likert %>% str()
# Class 'labelled'  atomic [1:100] 4 3 4 3 1 3 4 3 4 3 ...
# ..- attr(*, "labels")= Named num [1:5] 1 2 3 4 5
# .. ..- attr(*, "names")= chr [1:5] "Strongly Agree" "Agree" "Neutral" "Disagree" ...
# ..- attr(*, "label")= chr "Likert Scale"
```

Is there a way to preserve the variable label if I want to drop unused levels?

```{R}
likert %>% as_factor() %>% str()
# Factor w/ 5 levels "Strongly Agree",..: 4 3 4 3 1 3 4 3 4 3 ...
# - attr(*, "label")= chr "Likert Scale"
likert %>% as_factor() %>% droplevels() %>% str()
# Factor w/ 4 levels "Strongly Agree",..: 4 3 4 3 1 3 4 3 4 3 ...
```

**Comment by sjPlot** [comment]
You could use the `to_label()` function from the current [sjmisc-GitHub](https://github.com/sjPlot/sjmisc)-version:

    likert %>% to_label(., drop.levels = T) %>% str()
    >  Factor w/ 4 levels "Strongly Agree",..: 1 4 2 4 4 2 4 4 3 4 ...
    >  - attr(*, "label")= chr "Likert Scale"

A final release to CRAN is planned after the haven-update, because sjmisc already supports the _tagged NA_ feature from haven.

**Comment by dchiu911** [comment]
Thanks @sjPlot!
