### ISSUE TITLE
read_sas: "b7dat" and "b7cat" are inaccurate parameter names

### ISSUE THREAD

**Issue by evanmiller** [hadley/haven#214]
The file format names are sas7bdat ("SAS 7 Binary Data") and sas7bcat ("SAS 7 Binary Catalog"). Moving the `7` after the `b` does not make much sense. I would suggest renaming to one of:

* `sas7bdat`/`sas7bcat`
* `bdat`/`bcat`
* `data`/`catalog`
* `data_file`/`catalog_file`

**Comment by hadley** [comment]
Ooops! Thanks for spotting this
