### ISSUE TITLE
read_sas cannot find files on network drives

### ISSUE THREAD

**Issue by mlaviolet** [hadley/haven#215]
When I reran an old script, read_sas threw the following error:

Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat":
 The system cannot find the file specified

The path is fully qualified, pointing to a file on a network drive. Calling "file.exists" confirms the existence of the file. "read_sas" successfully reads files on my local drive where R is installed. Other functions can locate files in the same folder on my network drive. I'm thinking the issue arose with the most recent package update. The older read.sas7bdat from the "sas7bdat" package can also locate the network files. Please advise. Thanks!

**Comment by hadley** [comment]
What happens if you do `normalizePath("//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat")`?

**Comment by hadley** [comment]
It would also be helpful if you could give the results of `traceback()`

**Comment by mlaviolet** [comment]
I also encountered the issue with `read_spss` and `read_dta`. From the `readxl `package, `read_excel `seems to work.

`file.exists("//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat")`
[1] TRUE

`normalizePath("//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat")`
[1] "\\\\Hzndhhsvf2\\data\\OCPH\\EPI\\BHSDM\\Group\\BRFSS\\2013\\Asthma callback\\afa_nh13_adult_weighted_llcp.sas7bdat"
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat": The system cannot find the file specified

`test1 <- read_sas("//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat")`
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat": The system cannot find the file specified

`traceback()`
4: normalizePath(path, mustWork = TRUE)
3: clean_path(b7dat)
2: df_parse_sas(clean_path(b7dat), clean_path(b7cat))
1: read_sas("//Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat")`



```

**Comment by hadley** [comment]
Can you please try writing the path like `\\\\Hzndhhsvf2/data/OCPH/EPI/BHSDM/Group/BRFSS/2013/Asthma callback/afa_nh13_adult_weighted_llcp.sas7bdat``

**Comment by hadley** [comment]
Regardless, this is a problem with `normalizePath()`, not haven, so unfortunately I can't fix it here.
