### ISSUE TITLE
Invalid timestamp string

### ISSUE THREAD

**Issue by ekstroem** [hadley/haven#216]
Hi, 

Trying to read in a Stata dataset I just received from a client.

    > read_dta("healthy_lifestyle_v3.dta")
    Invalid timestamp string (length=17): 30 JUN 2016 11:11
    Error: Failed to parse healthy_lifestyle_v3.dta: The file's timestamp string is invalid.

Now the timestamp looks fairly reasonable in my view, and the file is readable with the `readstata13` package although I haven't done anything besides just seeing that I didn't get an error. I don't have Stata and cannot really check the file content but if anyone wants to use it for bug hunting it can be found here:

[
biostatistics.dk/data/stata.dta](http://biostatistics.dk/data/stata.dta)

**Comment by hadley** [comment]
Have you tried the dev version of staticdocs?

**Comment by ekstroem** [comment]
Ahem ... the link should be working now if that was what you were hinting at :)

Otherwise I haven't heard of staticdocs before and am slightly baffled as to how it would help with the stata file.

**Comment by hadley** [comment]
Sorry that was a think-o, I meant dev version of haven.

**Comment by ekstroem** [comment]
Ah! That makes me less confused (however `staticdocs` looks quite interesting) .  Yup. Just reinstalled to make sure:

    devtools::install_github("hadley/haven", force=TRUE)

and get the same result as before. 

Here's the session info:

```
> devtools::session_info()

Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin13.4.0        
 ui       X11                         
 language (EN)                        
 collate  C                           
 tz       Europe/Copenhagen           
 date     2016-08-30                  

Packages -----------------------------------------------------------------------
 package    * version    date       source                       
 Rcpp         0.12.6     2016-07-19 CRAN (R 3.3.0)               
 assertthat   0.1        2013-12-06 CRAN (R 3.3.0)               
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.0)               
 digest       0.6.10     2016-08-02 CRAN (R 3.3.0)               
 haven      * 0.2.1.9000 2016-08-30 Github (hadley/haven@b158f48)
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.0)               
 readr        1.0.0      2016-08-03 cran (@1.0.0)                
 tibble       1.2        2016-08-26 CRAN (R 3.3.0)               
 withr        1.0.2      2016-06-20 CRAN (R 3.3.0)            
```

**Comment by evanmiller** [comment]
Hi, it appears ReadStat is choking on the uppercase month name. Fixed in https://github.com/WizardMac/ReadStat/commit/6c4f3066778280041fa9ab6c40f902326ce1e66d

**Comment by ekstroem** [comment]
Thanks!
