### ISSUE TITLE
Writing stat file in old format (e.g. Stata 8)

### ISSUE THREAD

**Issue by larmarange** [hadley/haven#217]
Since the support of Stata 14, it seems that `write_dta` export data in Stata 14 format. The problem is that it's not possible to open the file with an older version of Stata and/or with other software that supports Stat format but usually only older version.

Therefore, would it be possible to have an option allowing to export a file to an older version of Stata?

**Comment by evanmiller** [comment]
@hadley this can be specified with readstat_writer_set_file_format_version(), passing in DTA version 105-118.

**Comment by hadley** [comment]
How do dta versions correspond to stata versions? (just subtract off 100?)

What's the most common version of stata? Should I default to stata 13?

**Comment by evanmiller** [comment]
There's not a simple correspondence. I can add some C constants but the DTA docs state:

       Format        Current as of
        ---------------------------------------
          118         Stata 14
          117         Stata 13 
          116         internal; never released
          115         Stata 12
          114         Stata 10
          113         Stata  8
        ---------------------------------------

ReadStat supports back to 105 which I think is Stata 4 or 5.

In ReadStat I default to Stata 14 because this has the best Unicode and long string support.

In Wizard I offer three options with this summary:

```
Stata 14 (released 2015): Full Unicode, strings up to 2045 bytes
Stata 13 (released 2013): No Unicode, strings up to 2045 bytes
Stata 10 (released 2007): No Unicode, strings up to 244 bytes
```
