### ISSUE TITLE
Missing variable type in sav files

### ISSUE THREAD

**Issue by dgromer** [hadley/haven#23]
When writing a sav file using

```r
data <- data.frame(Var = c(1, 2, 3))
haven::write_sav(data, "numeric_haven.sav")
```

in the resulting file, the variable does not have any type (should be numeric). Maybe the reason is me using a German version of SPSS, that expects "," as decimal separator instead of "."?

Here's the file written with haven:
https://github.com/dgromer/misc/blob/master/numeric_haven.sav

and how it should look like (created with SPSS):
https://github.com/dgromer/misc/blob/master/numeric_spss.sav

**Comment by evanmiller** [comment]
This issue should be fixed with this ReadStat commit:

https://github.com/WizardMac/ReadStat/commit/9bc3ad11408b99429e30fce98ac21f166c23085a

**Comment by dgromer** [comment]
Yes, works for me when using the updated version of readstat_sav_write.c, thanks!
