### ISSUE TITLE
Writing string variable to sav results in data1205 error

### ISSUE THREAD

**Issue by dgromer** [hadley/haven#24]
When writing a sav file using

```r
data <- data.frame(Var = c("One", "Two", "Three"), stringsAsFactors = FALSE)
haven::write_sav(data, "string_haven.sav")
```

I get the following error when opening with SPSS (DATA1205): http://www-01.ibm.com/support/docview.wss?uid=swg21512643

File written with haven:
https://github.com/dgromer/misc/blob/master/string_haven.sav

File written with SPSS:
https://github.com/dgromer/misc/blob/master/string_spss.sav

**Comment by hadley** [comment]
@evanmiller I can't see what I could do be doing wrong here, and the data frame round-trips ok.

**Comment by evanmiller** [comment]
I'm not 100% sure what's causing this, but I have some theories. Try this commit:

https://github.com/WizardMac/ReadStat/commit/bb1c94a318c543d7772fe5d70eae3e0c052d678b

**Comment by dgromer** [comment]
It works with the update, however one issue remains:

![Uploading spss_variable_width.png . . .]()

The variable width is set to 0 in the read_sav-written file, so SPSS does not allow to enter values in the data editor (because it expects strings of length zero)

**Comment by evanmiller** [comment]
Try this commit:

https://github.com/WizardMac/ReadStat/commit/6aca5c560269bfd89a98d7083a91c07d6600f681

**Comment by dgromer** [comment]
Yes works. Width is now set to 5 in my example (the length of the longest string I guess)
