### ISSUE TITLE
RStudio Viewer does not print imported data frames

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#28]
When loading an SPSS file with `read_spss` or `read_sav`, I can't view the data frame in the RStudio Viewer.

    > View(x)
    Error: `x` and `labels` must be same type

Using RStudio Version 0.99.283 on Win 7.

**Comment by dgromer** [comment]
Works for me with a file of mine in RStudio 0.98.1102. Maybe it's a problem with the new data viewer in RStudio 0.99 or the problem is caused by a specific variable in your data set?

**Comment by hadley** [comment]
Works for me - could you please file a reproducible example?

**Comment by sjPlot** [comment]
I sent you a mail. I guess it has to do with the `labelled` class, NA's in the imported data frame and incompatibilities of the labelled-class with base-functions like `summary` or `na.omit`. Reproducible examples explained in my mail.

**Comment by NilsEnevoldsen** [comment]
Can this issue be reopened now that #46 gives a reproducible example? I'm encountering the error with Part B of the [Nigeria - General Household Survey 2009, Fifth Round](http://www.nigerianstat.gov.ng/nada/index.php/catalog/36/study-description).

**Comment by dsself** [comment]
I am having the same issue using the Stata version of the [Authoritarian Regime Dataset](https://sites.google.com/site/authoritarianregimedataset/data) in haven 0.2.0 in R studio 0.99 using Windows 7. 

I tried using the dev version but got this error and couldn't figure out how to approach the issue. 

`Error in .Call("haven_df_parse_dta", PACKAGE = "haven", filename) : 
  "haven_df_parse_dta" not available for .Call() for package "haven"`

**Comment by briatte** [comment]
Same here, using RStudio 0.99.486 on Mac OS X 10.9.5 while working on Stata data.

**Comment by jc2445** [comment]
Hi, so how can this error labelled thing be solved? I try to subset non-missing rows of the imported spss data, but cannot use !is.na or omit.na[].

**Comment by drgmerchant** [comment]
I am having this issue as well, and the only way I can fix it is by not invoking tidyverse. I don't understand the labelling issue - is this an attribute of some of my data's vectors?

**Comment by hadley** [comment]
If you need help, please file an minimum reproducible issue. Commenting on closed issues is not usually a fruitful approach.

**Comment by drgmerchant** [comment]
Yes, I agree. I'm new to posting here and asking questions. It's a long dataset with lot's of variables that is an .RData file I've created in other scripts from .csv files. I will try to re-create the problem generating some sample data that is similar.
