### ISSUE TITLE
Can't properly acces data frame columns from imported files.

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#29]
When I import data with haven, the returned object from read functions has following class-attributes:

    > class(x)
    [1] "tbl_df"     "tbl"        "data.frame"

When accessing a table column, still a data frame is returned:

    str(x[, 6])
    Classes ‘tbl_df’ and 'data.frame':	1567 obs. of  1 variable:
     $ sex:Class 'labelled'  atomic [1:1567] 1 1 1 1 1 1 1 1 1 1 ...
      .. ..- attr(*, "label")= chr "Geschlecht der antwortenden Person"
      .. ..- attr(*, "labels")= Named int [1:2] 0 1
      .. .. ..- attr(*, "names")= chr [1:2] "männlich" "weiblich"

I would assume that I either retrieve an atomic vector with attributes or a vector of class `labelled`...

**Comment by hadley** [comment]
That only happens if you also have dplyr loaded (and is standard behaviour for dplyr). Use `x[[6]]` or (better) x$name to extract the column.

**Comment by sjPlot** [comment]
Ok, thanks! dplyr was loaded via another package. I use x[[6]] now - $name doesn't help, because I only have column indices.
