### ISSUE TITLE
read_spss() imports value labels for multiple declared missings

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#33]
In SPSS, you can assign multiple missing values, e.g. "8" as "not applicable" or "9" for "real missing". `read_spss()` would set both 8 and 9 to `NA` in the imported data.frame, however, if a value label for "8" is set, it is also imported - thus, you have one more value label than values.

Example:

"Do you live in partnership?"

1 - yes
2 - no
8 - not applicable (was asked before if married) -> declared as "8" missing
9 - missing -> declared as "9" missing, but not labelled

Now read_spss() imports this as vector with two values (1/2) and NA's, but three value labels (yes/no/not applicable).

This is no serious bug, but I wonder if it would be possible to distinguish whether an SPSS-declared "missing value" is either a "real" missing or a "not applicable" declared missing. In SPSS you do this e.g. to get valid frequency counts for yes/no answers, but still having the information how much "real" missings you have...

**Comment by evanmiller** [comment]
@hadley -- right now ReadStat squashes all missing values into a NULL. I'm open to changing the API to let you access the original value even when it is missing. (I.e., make readstat_value_t a struct with an is_missing flag.)

Additionally it may be worth reporting the missingness criteria, which for SAV consists of a single missing value and/or a contiguous range of values regarded as missing. I'm not sure if this would be useful for R data frames -- but for my own software knowing the underlying criteria would be more helpful than having an is_missing flag for each observation.

**Comment by hadley** [comment]
@evanmiller I agree it would be nice to have, but given that there's no great way of representing this data in R (or working with it once you have a representation), it's low priority for me.

**Comment by sjPlot** [comment]
I agree - but could redundant labels (above example 'not applicable') be omitted (hence, only two labels are imported)?

**Comment by hadley** [comment]
Hmmm, I need to think this through. ReadStat API now has:

> readstat_value_is_missing is now supplemented with two more functions to distinguish system-missing > (e.g. NaN values) from values that are considered missing on account of the missing value definitions:
>
> int readstat_value_is_system_missing(readstat_value_t value);
> int readstat_value_is_considered_missing(readstat_value_t value);

Maybe `read_spss()` could gain an option to switch between either recording as NA in R, or recording as original level.

**Comment by larmarange** [comment]
It would be great. 

Would also be great to have an appropriate attribute to store information about missing values (similarly to variable and value labels). Therefore, it would be possible to import the code (without transforming them to `NA`) and having a function to easily transform declared missing values to `NA`.

So far, `read.spss` and `read.dta` are using different attributes to store this information.

**Comment by hadley** [comment]
I think the labelled class could probably get an additional `is_na` attribute that determine if a value should be converted to missing. I think the default behaviour will remain as is (since it ensures that (e.g.) mean will give the correct result in the presence of missings), but you could request `preserve_na = TRUE` (not the best name) and it would create labelled classes that you could handle manually.

**Comment by dusadrian** [comment]
That would be great indeed, whatever the final solution is.
There is of course a universal (cross software) way of treating missing values using attributes. I am already working on such a solution in my DDIwR package, via a metadata standard called DDI (Data Documentation Initiative).
But that is post importing the data with read_spss() so the important thing right now is to have this function import missing data information.

**Comment by hadley** [comment]
@sjPlot @larmarange could either of you please create a minimal spss file that uses this sort of encoding? Need both a continuous and categorical variable

**Comment by hadley** [comment]
I think I've plumbed up everything correctly so that this should now work - you'll get a `labelled` object that more closely matches the semantics of SPSS/Stata. When you call `as_factor()` the missing values will all be converted to NA, unless you use `drop_na = FALSE` which will preserve the original values.

Please let me know if (a) this doesn't work or (b) the logic isn't that useful.

**Comment by larmarange** [comment]
You could try this file http://joseph.larmarange.net/spss_missing.sav

I tested quickly. So you introduced a new attribute `attr(*, "is_na")`. However, missing values doesn't always have a label. They could be define as discrete values or has a range of values or as a range and a discrete value (see the SPSS file).

Therefore, I'm not sure that using your `is_na` attribute as currently (i.e. a TRUE/FALSE value to the labels) is the best solution.

Note: I have done a quick test today, no values has been identified as missing.

**Comment by hadley** [comment]
I don't have access to SPSS, so it would be most helpful if you could tell me exactly how the variables in the file are encoded.

**Comment by larmarange** [comment]
![image](https://cloud.githubusercontent.com/assets/966307/8309328/2c270cee-19ca-11e5-94ec-eecdf7e65e70.png)

![image](https://cloud.githubusercontent.com/assets/966307/8309338/36b54946-19ca-11e5-912c-54156b779270.png)

Would it be enough?

**Comment by larmarange** [comment]
![image](https://cloud.githubusercontent.com/assets/966307/8309347/5111fdc0-19ca-11e5-880b-c98ce364d68e.png)

And the data

**Comment by sjPlot** [comment]
I just downloaded the latest haven-build from GitHub, but it does not seem to work properly (or do I have to care about the read_stat library as well?).

I have set up a small [SPSS file](https://www.dropbox.com/s/uvdp8cemf6avu0y/Missings.sav?dl=0)

Here is the data:
![spss_2](https://cloud.githubusercontent.com/assets/4901179/8316583/5473824e-19f8-11e5-800c-49aced2feb31.png)

and here the labeling / missing declaration:
![spss_1](https://cloud.githubusercontent.com/assets/4901179/8316589/602eb540-19f8-11e5-80c8-e736f25a1bea.png)

  * So, _First, Second,_ to _Fifth_ have all different missing values declared, but these variables **have no value labels**
  * *First_b*, *Second_b* to *Fifth_b* have all different missing values declared, **and** these variables **do have value labels**
  * *First_c*, *Second_c* to *Fifth_c* **have all different missing values declared, but **no missing values in the data** and  these variables **have no value labels**

Does this help you?

**Comment by hadley** [comment]
Yes, that's useful. 

* I don't see how to handle unlabelled variables with multiple missings, so for now, these should be translated directly to `NA`.

* I may have misunderstood how missings are flagged for labelled variables. @evanmiller should I expect `readstat_value_is_considered_missing(value)` to be true when called from the `value_label_handler`?

* You're saying that these are not labelled in the spss file, but are being labelled in R?

**Comment by larmarange** [comment]
Technically, there are missing values, and not missing labels.  

An option would be to store the list of missing values in `attr(*, 'is_na')`, i.e. `c(5,8,9)` for example for a list of discrete missing values, without trying to associate a missing value with a value label, as the two informations are independent.

**Comment by larmarange** [comment]
Just a note: when the variable is numeric, you can specify in SPSS discrete missing values or a range of missing values (with or without a discrete value). When the variable is character, you can specify only discrete missing values.

**Comment by larmarange** [comment]
Don't know yet what would be the best way to store the two kind of information (discrete missing values and a range of missing values). Should we use two attributes (e.g, `is_na` and `is_na_range`) ?

**Comment by larmarange** [comment]
NB: Stata could also deal with multiple missing values for numeric variables, coded as `.a`, `.b`, etc. However, I don't know if you can apply a value label to them.

**Comment by dusadrian** [comment]
I have a solution for any number of missing values (not just 27), using attributes.
I am storing (see below):
- one component for each variable
- each component has one subcomponent for each missing type
- each subcomponent has exactly two further subcomponents:
      - one that stores the original values of the missing
      - one that stores the IDs of the unique id variable where the missings are found

In the case of the Missing1 variable, we have a missing value of 5 which is found where IndividualId is equal to 3.

Personally, missing values with no labels are equivalent to undeclared system missings. There are completely useless for any practical purpose, therefore I think only declared missing values with labels should be treated.

One other thing: it might very well be that some missing values are left undeclared in the SPSS file but they are declared in other metadata files (e.g. DDI). It is off this topic, but it touches important documentation points and I intend to combine attributed with DDI as an import/export tool.

> attr(spssmiss, "missing types")
$MISSING1
$MISSING1$`I don't have a TV`
$MISSING1$`I don't have a TV`$values
[1] 5

$MISSING1$`I don't have a TV`$cases
[1] 3


$MISSING1$`Don't know`
$MISSING1$`Don't know`$values
[1] 8

$MISSING1$`Don't know`$cases
[1] 4


$MISSING1$`Missing (on paper form)`
$MISSING1$`Missing (on paper form)`$values
[1] 9

$MISSING1$`Missing (on paper form)`$cases
[1] 5



$MISSING2
$MISSING2$`I don't have videogames`
$MISSING2$`I don't have videogames`$values
[1] 5

$MISSING2$`I don't have videogames`$cases
integer(0)


$MISSING2$`Don't know`
$MISSING2$`Don't know`$values
[1] 8

$MISSING2$`Don't know`$cases
[1] 2


$MISSING2$`Missing (on paper form)`
$MISSING2$`Missing (on paper form)`$values
[1] 9

$MISSING2$`Missing (on paper form)`$cases
[1] 3



$MISSING4
$MISSING4$Missing
$MISSING4$Missing$values
[1] 9

$MISSING4$Missing$cases
[1] 3



$MISSING5
$MISSING5$Missing
$MISSING5$Missing$values
[1] 9

$MISSING5$Missing$cases
integer(0)

**Comment by larmarange** [comment]
> Personally, missing values with no labels are equivalent to undeclared system missings. There are completely useless for any practical purpose, therefore I think only declared missing values with labels should be treated.

Just to provide a feedback from different data sources. The way datasets from surveys are provided by different research centres could differ substantially. I have already seen datasets with missing values specified in SPSS but value labels not specified (as a separate document was describing all variables).

It's sometimes difficult to find a way to import data in R without changing them. However, the assumption that missing values with no labels are equivalent to undeclared system missings is not always true.

**Comment by evanmiller** [comment]
> I may have misunderstood how missings are flagged for labelled variables. @evanmiller should I expect readstat_value_is_considered_missing(value) to be true when called from the value_label_handler?

@hadley At present `readstat_value_is_considered_missing` does not return true in the value label handler.

**Comment by sjPlot** [comment]
@hadley no, I was only describing the SPSS dataset, ie I have not labelled all of them in the SPSS file.

**Comment by dusadrian** [comment]
@larmarange  Fair enough, and that goes in line with my second note that sometimes a different document describes the metadata.
Using attributes, another generic missing type called "undeclared" would solve this. Will implement that in my DDIwR package, thanks.

**Comment by dusadrian** [comment]
@larmarange Oh, and yes, in my version of the imported object, <all> missing values are changed to NA. The attributes store which variable had which type of missing, having which value in the original dataset, on which position(s). This provides a complete information system that is perfectly consistent with base R and it can be used for any practical purpose (including to export the R object to any other statistical software).

**Comment by larmarange** [comment]
@dusadrian it seems in your proposal that it could increase substantially the size of a data.frame as you copy in an attribute as you copy all cases. Secondly, you store the information at the data.frame level and not at the variable level. Thirdly, you don't have always a unique identifier for each row. If the identifier is the row number, the information will be lost once you will sort your data.frame.

What I really like with the labelled class is that it's not changing your microdata. You keep the exact codes used in the original SPSS/Stata file and your able, later, to transform your data into a factor with a dedicated function.

My feeling is that the same approach should be used for missing values. **Microdata** should never be changed when importing a data set, and attributes used to store **metadata**.

So, when importing an SPSS file, declared missing values should not be changed to `NA` but we should keep the original code. Then, we could provide a function like `missing2NA` that will return a vector with all declared missing values transformed to `NA`. (we could also imagine that this function could be apply also to a whole dataset).

Finally, we need also to consider that *value labels* and *declared missing values* are two different kind of metadata, implying that attributes for missing values could also be applied to non labelled variables (similarly, variable labels could be attached to a non labelled variable).

**Comment by dusadrian** [comment]
@larmarange 
It would increase the size of the dataset, but not substantially (in any case, completely manageable for decent size datasets) because it doesn't copy >all< cases but only those where the labelled (or declared) missings are found. The vast majority is cells are simple system missings (NAs) and those are not stored but left as they are.
Right, there is not always a unique identifier (and certainly the identifier should not be the row number), but that can be created.

I am not sure how would anyone preserve Stata-type missing values in R, like ".a" or ".r"
The whole point of my system is to provide a universal exchange platform between very different software. It is not a competitor of haven, but rather it would rely on haven to import, then create that attributes list. Of course the attributes can be stored at variable level as well, it was just for convenience to have one big list for all variables, which also contains (not shown in my example) variable labels and value labels as well. 
No matter how they are stored, the important thing is they can be used with ease.

Just to conclude, it is impossible to keep the original code when exporting from Stata to SPSS: they are simply too different. SAS is also very different from Stata in treating (ie storing) missing values: one uses upper (towards plus infinity) internal values, the other uses lower (towards minus infinity) internal values.
This is why such a system is needed, to universally cover all possible situations.

As a bonus argument, it is (or can be used as) a standard. DDI as a metadata storage standard cannot possibly account for all possible current and future internal systems of various statistical software (it would not be >standard< anymore). But the method I've shown, using attributes, is perfectly consistent with the DDI standard... I hope that explains what I have in mind.

**Comment by dusadrian** [comment]
Oh and yes, using attributes it really doesn't matter if the original variable is labelled or not: storing the missing types and where they are found is completely independent of the variable itself.

**Comment by larmarange** [comment]
In all cases, whatever the solution implemented in `haven`, it would be at least useful to have in `read_spss` an option equivalent to `use.missings` in `read.spss` from `foreign`, i.e. letting the user decide if user-defined missing values in the SPSS file should be converted to `NA` or not

**Comment by dusadrian** [comment]
Indeed.
That was my initial opened issue (closed as a duplicated of this one):
https://github.com/hadley/haven/issues/74

On Sat, Jul 4, 2015 at 9:39 AM, Joseph <notifications@github.com> wrote:

> In all cases, whatever the solution implemented in haven, it would be at
> least useful to have in read_spss an option equivalent to use.missings in
> read.spss from foreign, i.e. letting the user decide if user-defined
> missing values in the SPSS file should be converted to NA or not
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/haven/issues/33#issuecomment-118470934>.
>



-- 
Adrian Dusa
University of Bucharest
Romanian Social Data Archive
Soseaua Panduri nr.90
050663 Bucharest sector 5
Romania

**Comment by evanmiller** [comment]
@hadley This commit will mark missing values before passing them to the value_labels_handler:

https://github.com/WizardMac/ReadStat/commit/3c71dba2c85792aa3dfdf9f8faadcab16ebb05b7

**Comment by sjPlot** [comment]
@hadley Could you also update the ReadStat sources in the haven-package? That would be very great, so I can test the new read-features...

**Comment by larmarange** [comment]
Would it be possible to reconsider an attribute `"missing_values"` containing the list of values that need to be considered as self-defined missing values, instead of the current `"is_na` attribute?

Even if it's not perfect, it would be at least more flexible than the current `"is_na` attribute.

1. missing values could be defined for a non labelled variable
2. when importing from SPSS it could take the list of discrete missing values and the list of observed values fitting in the range of missing values defined in SPSS. 
3. when exporting to SPSS, they will be defined as discrete missing values
4. when importing from Stata, I'm not sure there is a simple solution to deal with `.a`, '.b'.

Or do you have something else in mind?

**Comment by sjPlot** [comment]
Though I would say that it's beneficial to have multiple declared missing of non-labelled values (as proposed by you in 1.), I would say it's a bad habit to not label multiple missing values - you can't see the qualitative differences between these values, if they're not labelled (refused response, not applicable, real missing?).

**Comment by sjPlot** [comment]
It is also important to keep this information (about missing values) when writing back to sav or other formats. @evanmiller or @hadley: would you say it is possible to write to SPSS and declare multiple values as missing, including labelling them?

I'm thinking of collaborative work with colleagues, who use SPSS. I import the data into R, do some recodings and analyses, and then write back the data frame to SPSS-sav, so other colleagues may work with the new, recoded variables without doing the same work again. This "interface" between R and SPSS (and others) is a very big advantage! Especially towards promoting R, because we are no longer locked into one software package (SPSS).

**Comment by evanmiller** [comment]
@sjPlot Defining custom missingness conditions is currently not supported in ReadStat.

**Comment by larmarange** [comment]
@sjPlot  I agree it's good practice to provide a label for self-defined missing values. However, it's not always the case (and not mandatory in SPSS) and we also have to deal with the data as they are provided.

On a second hand, having a "missing_values" attribute which is a list of values rather that a logical vector is easier to manipulate when you are doing transformation on labels (like adding a label or removing a label).

**Comment by dusadrian** [comment]
@sjPlot:
There is another possibility to transfer the new work to SPSS, via setup
files.
The DDIwR package takes a list of metadata (or an XML file describing it)
and produces an SPSS syntax file with commands to create labels, including
various missing values.

On Wed, Jul 8, 2015 at 12:09 PM, Daniel Lüdecke <notifications@github.com>
wrote:

> It is also important to keep this information (about missing values) when
> writing back to sav or other formats. @evanmiller
> <https://github.com/evanmiller> or @hadley <https://github.com/hadley>:
> would you say it is possible to write to SPSS and declare multiple values
> as missing, including labelling them?
>
> I'm thinking of collaborative work with colleagues, who use SPSS. I import
> the data into R, do some recodings and analyses, and then write back the
> data frame to SPSS-sav, so other colleagues may work with the new, recoded
> variables without doing the same work again. This "interface" between R and
> SPSS (and others) is a very big advantage! Especially towards promoting R,
> because we are no longer locked into one software package (SPSS).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/haven/issues/33#issuecomment-119508416>.
>



-- 
Adrian Dusa
University of Bucharest
Romanian Social Data Archive
Soseaua Panduri nr.90
050663 Bucharest sector 5
Romania

**Comment by sjPlot** [comment]
I have found a syntax somewhere, which also creates SPSS-syntax-files to label a sac-file that has been written from R - however, that's not really comfortable. The write-function of the haven-package is much better for a smooth workflow.

**Comment by evanmiller** [comment]
I've added some code to ReadStat to support custom missing values:

https://github.com/WizardMac/ReadStat/commit/8a6835d119025a2729bd2ffafb4a2463ec0687b8

Note that the SAV format only allows up to 3 discrete missing values per variable (or one range and one value). I'd like to support ranges in the future, but the logic is a little more involved.

**Comment by evanmiller** [comment]
And here's support for ranges:

https://github.com/WizardMac/ReadStat/commit/3bf2eb464e2ae75b79f3fef17b0eb29790325af5

If a range is present in the missingness conditions, the code will emit the first missing range and the first missing value. Otherwise it will emit up to three missing values. @hadley use `HUGE_VAL` and `-HUGE_VAL` to specify open-ended ranges.

**Comment by hadley** [comment]
@larmarange as far as I can tell `read_spss(user_na = TRUE)` now correctly preserves the user defined missings in http://joseph.larmarange.net/spss_missing.sav

**Comment by larmarange** [comment]
Looks perfect.

Thanks a lot @hadley
