### ISSUE TITLE
write_dta leads to R crashing 

### ISSUE THREAD

**Issue by fhollenbach** [hadley/haven#37]
Created a data frame using simulated data and tried to save it as a dta file, this led R to crash with segfault error. Using R version 3.1.2 on a Mac with OSX 10.10.2.

Example code:
```R
library(haven)
library(plyr)

set.seed(12345)
N=300
var1 = rnorm(N,0,1.5)
var2 = rnorm(N,2,5)
var3 = runif(N,-10,10)

dataForStata = data.frame(var1,var2,var3)
names(dataForStata) = c("var1","var2","var3")
write_dta(dataForStata,path="~/Desktop/")
```

Running the code produces the following error:
```R
> write_dta(dataForStata,path="~/Desktop/")

 *** caught segfault ***
address 0x68, cause 'memory not mapped'

Traceback:
 1: .Call("haven_write_dta", PACKAGE = "haven", data, path)
 2: write_dta(dataForStata, path = "~/Desktop/")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

R session info:
```R
sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin14.0.0 (64-bit)

locale:
[1] en_US/en_US/en_US/C/en_US/en_US

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plyr_1.8.1       haven_0.1.1.9000

loaded via a namespace (and not attached):
[1] Rcpp_0.11.4
```

**Comment by afleishman** [comment]
You need to specify the file name... change your last line of code to

>write_dta(dataForStata,path="~/Desktop/dataForStata.dta")

**Comment by fhollenbach** [comment]
That doesn't solve the issue, the same thing happens. The help file does ask for a path, not filename.

**Comment by afleishman** [comment]
weird, worked for me when I specified file name. I'm on a Windows machine though.

**Comment by fhollenbach** [comment]
Ha, I just figured it out. You were correct, but the path also cannot be specified with "~" in it. 
So "write_dta(dataForStata,path="/Users/fhollenbach/Desktop/dataForStata.dta")" works on the Mac. 
Thanks! I am closing the issue for now?

**Comment by afleishman** [comment]
Glad it worked out :). I had a similar issue on Ubuntu... I forgot the first '/' at the beginning of the path and it was crashing every time I'd run the code.

**Comment by hadley** [comment]
It shouldn't crash on a malformed path

**Comment by rubenarslan** [comment]
Can confirm this goes away in `write_sav` when switching from tilde expansion to full path (OS X).
