### ISSUE TITLE
labels versus format

### ISSUE THREAD

**Issue by bethatkinson** [hadley/haven#39]
Not a bug - just a comment that I found the labelled function a bit confusing because of the name.  So “labelled” is similar to a SAS format, versus a SAS “label”, which I was happy to see does still come across.  Both are useful concepts and it would really be nice to have both supported.  

Also, I noticed with subsetting the data that the “label” attribute is lost but not the “labels” attribute.    Any chance of adding in the “label” concept somehow?   It would be nice to not lose that information and it would be nice to have a wrapper function that adds/extracts the information.

Thanks for the consideration.  

<pre><code>
d2$death <- labelled(d2$status, labels=c(Censored=0, Dead=1))
attributes(d2$death)
$label
[1] "Vital Status"
$labels
Censored     Dead 
       0        1 
$class
[1] "labelled"
</pre></code>

**Comment by sjPlot** [comment]
May I promote my [sjPlot package](github.com/sjPlot/devel) here, which aims at making tables and plots easier / more comfortable? It also offers wrapper functions for setting/getting value and variable labels. It both supports `foreign` package style (`value.labels` and `variable.label` attributes) as well as `haven` package style (`labels` and `label` attributes).

If you use these functions, you can set which attribute-style should be used by default with `options(value_labels = "haven")`.

    library(sjPlot)
    options(value_labels = "haven") # labels attributes in haven-style
    death <- labelled(c(0,1,1,0,1,NA,1), labels=c(Censored=0, Dead=1))
    death <- set_var_labels(death, "Todesfälle") # set variable label attribute
    sjp.frq(death, na.rm = F) # plot variable, including NA

![rplot](https://cloud.githubusercontent.com/assets/4901179/6598604/0f7079bc-c805-11e4-8c3b-b1c71ffefc41.png)

**Comment by bethatkinson** [comment]
Thanks for the words to describe <code>value.labels</code> versus <code>variable.label</code> attributes.  That is helpful.  I'm still hoping that <code>haven</code> can automatically recognize these when reading data from SAS and will not lose the variable.label  attribute when subsetting the data.  I'll take a closer look at your package, too.

**Comment by sjPlot** [comment]
Just to clarify, `variable.label` is the attribute's name used by the `foreign` package (when using `read.spss` e.g.), while `haven` uses `label` as attribute's name.
I'm not sure which function you use for subsetting, but if I recall right, @hadley is planning to update `dplyr` so label-attributes won't get lost when subsetting data.

**Comment by bethatkinson** [comment]
I was just subsetting using the old-fashioned way
<pre><code>
d3 &lt;- d2[d2$sex=='F',]
</pre>
</code>

Using this route, the <code>label</code> attribute is lost but the <code>labels</code> attribute created using <code>haven</code> is retained.   The <code>label</code> was created in SAS and retained when using <code>sas.get</code> to import the data.
