### ISSUE TITLE
Include variable and value labels

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#4]
It would be nice if value and variable labels would be imported as well, e.g. by setting them as data frame attributes (like `read.spss` from `foreign` package does):

***Example of read.spss***

'data.frame':	908 obs. of  26 variables:
 $ c12hour : num  16 148 70 168 168 16 161 110 28 40 ...
 $ e15relat: atomic  2 2 1 1 2 2 1 4 2 2 ...
  ..- attr(*, "value.labels")= Named chr  "8" "7" "6" "5" ...
  .. ..- attr(*, "names")= chr  "other, specify" "cousin" "nephew/niece" "ancle/aunt" ...
 $ e16sex  : atomic  2 2 2 2 2 2 1 2 2 2 ...
  ..- attr(*, "value.labels")= Named chr  "2" "1"
  .. ..- attr(*, "names")= chr  "female" "male"
 $ e17age  : num  83 88 82 67 84 85 74 87 79 83 ...
 $ e42dep  : atomic  3 3 3 4 4 4 4 4 4 4 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "severely dependent" "moderately dependent" "slightly dependent" "independent"
 $ c82cop1 : atomic  3 3 2 4 3 2 4 3 3 3 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "always" "often" "sometimes" "never"
 $ c83cop2 : atomic  2 3 2 1 2 2 2 2 2 2 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "Always" "Often" "Sometimes" "Never"
 $ c84cop3 : atomic  2 3 1 3 1 3 4 2 3 1 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "Always" "Often" "Sometimes" "Never"
 $ c85cop4 : atomic  2 3 4 1 2 3 1 1 2 2 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "Always" "Often" "Sometimes" "Never"
 $ c86cop5 : atomic  1 4 1 1 2 3 1 1 2 1 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "Always" "Often" "Sometimes" "Never"
 $ c87cop6 : atomic  1 1 1 1 2 2 2 1 1 1 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "Always" "Often" "Sometimes" "Never"
 $ c88cop7 : atomic  2 3 1 1 1 2 4 2 3 1 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "Always" "Often" "Sometimes" "Never"
 $ c89cop8 : atomic  3 2 4 2 4 1 1 3 1 1 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "always" "often" "sometimes" "never"
 $ c90cop9 : atomic  3 2 3 4 4 1 4 3 3 3 ...
  ..- attr(*, "value.labels")= Named chr  "4" "3" "2" "1"
  .. ..- attr(*, "names")= chr  "always" "often" "sometimes" "never"
 $ c160age : num  56 54 80 69 47 56 61 67 59 49 ...
 $ c161sex : atomic  2 2 1 1 2 1 2 2 2 2 ...
  ..- attr(*, "value.labels")= Named chr  "2" "1"
  .. ..- attr(*, "names")= chr  "Female" "Male"
 $ c172code: atomic  2 2 1 2 2 2 2 2 NA 2 ...
  ..- attr(*, "value.labels")= Named chr  "3" "2" "1"
  .. ..- attr(*, "names")= chr  "high level of education" "intermediate level of education" "low level of education"
 $ c175empl: atomic  1 1 0 0 0 1 0 0 0 0 ...
  ..- attr(*, "value.labels")= Named chr  "1" "0"
  .. ..- attr(*, "names")= chr  "yes" "no"
 $ barthtot: num  75 75 35 0 25 60 5 35 15 0 ...
 $ neg_c_7 : num  12 20 11 10 12 19 15 11 15 10 ...
 $ pos_v_4 : num  12 11 13 15 15 9 13 14 13 13 ...
 $ quol_5  : num  14 10 7 12 19 8 20 20 8 15 ...
 $ resttotn: num  0 4 0 2 2 1 0 0 0 1 ...
 $ tot_sc_e: num  4 0 1 0 1 3 0 1 2 1 ...
 $ n4pstu  : atomic  0 0 2 3 2 2 3 1 3 3 ...
  ..- attr(*, "value.labels")= Named chr  "8" "7" "6" "5" ...
  .. ..- attr(*, "names")= chr  "other, specify" "cousin" "nephew/niece" "ancle/aunt" ...
 $ nur_pst : atomic  NA NA 2 3 2 2 3 1 3 3 ...
  ..- attr(*, "value.labels")= Named chr  "89" "88" "87" "86" ...
  .. ..- attr(*, "names")= chr  "other" "co-religionist" "volunteer" "neighbour" ...
 - attr(*, "variable.labels")= Named chr  "average number of hours of care for the elder in a week" "relationship to elder" "elder's gender" "elder' age" ...
  ..- attr(*, "names")= chr  "c12hour" "e15relat" "e16sex" "e17age" ...
 - attr(*, "codepage")= int 65001

***Same with haven***

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	908 obs. of  26 variables:
 $ c12hour : num  16 148 70 168 168 16 161 110 28 40 ...
 $ e15relat: num  2 2 1 1 2 2 1 4 2 2 ...
 $ e16sex  : num  2 2 2 2 2 2 1 2 2 2 ...
 $ e17age  : num  83 88 82 67 84 85 74 87 79 83 ...
 $ e42dep  : num  3 3 3 4 4 4 4 4 4 4 ...
 $ c82cop1 : num  3 3 2 4 3 2 4 3 3 3 ...
 $ c83cop2 : num  2 3 2 1 2 2 2 2 2 2 ...
 $ c84cop3 : num  2 3 1 3 1 3 4 2 3 1 ...
 $ c85cop4 : num  2 3 4 1 2 3 1 1 2 2 ...
 $ c86cop5 : num  1 4 1 1 2 3 1 1 2 1 ...
 $ c87cop6 : num  1 1 1 1 2 2 2 1 1 1 ...
 $ c88cop7 : num  2 3 1 1 1 2 4 2 3 1 ...
 $ c89cop8 : num  3 2 4 2 4 1 1 3 1 1 ...
 $ c90cop9 : num  3 2 3 4 4 1 4 3 3 3 ...
 $ c160age : num  56 54 80 69 47 56 61 67 59 49 ...
 $ c161sex : num  2 2 1 1 2 1 2 2 2 2 ...
 $ c172code: num  2 2 1 2 2 2 2 2 NaN 2 ...
 $ c175empl: num  1 1 0 0 0 1 0 0 0 0 ...
 $ barthtot: num  75 75 35 0 25 60 5 35 15 0 ...
 $ neg_c_7 : num  12 20 11 10 12 19 15 11 15 10 ...
 $ pos_v_4 : num  12 11 13 15 15 9 13 14 13 13 ...
 $ quol_5  : num  14 10 7 12 19 8 20 20 8 15 ...
 $ resttotn: num  0 4 0 2 2 1 0 0 0 1 ...
 $ tot_sc_e: num  4 0 1 0 1 3 0 1 2 1 ...
 $ n4pstu  : num  0 0 2 3 2 2 3 1 3 3 ...
 $ nur_pst : num  NaN NaN 2 3 2 2 3 1 3 3 ...

**Comment by hadley** [comment]
Do you have a copy of SPSS?

**Comment by hadley** [comment]
Shouldn't (e.g.) `n4pstu` be a factor?

**Comment by sjPlot** [comment]
Yes, `sex` should be a factor as well, but it seems that by default the `read.spss` functions imports all factors as `atomic`.

I could send you the SPSS file, via mail? It's 1.4mb large.

**Comment by hadley** [comment]
If you have spss, it would actually be way more useful to me if you could create a few small examples, each illustrating one problem:

* A 1x1 file with variable labels
* A 1x2 file containing a factor with levels a and b
* A 1x2 file containing a factor with levels a and b, but only with b observed

(FWIW those vectors aren't actually of class atomic, there's just a weirdness in their printing. I bet they're actually integers)

**Comment by sjPlot** [comment]
What do you mean by "1x2"? Row/Column (cases/variables)? I create these three files and send them to you.

Here's a screenshot of how the variables are entered into SPSS. As you can see, the entered data itself is numeric, however, the variables are indicated "Scale" (metric, continuous), "nominal" and "ordinal". All variables, which are nominal or ordinal are imported as `atomic` when you use the `read.spss` function from the `foreign` package.

![spss-screenshot](https://cloud.githubusercontent.com/assets/4901179/6062483/6c565ab8-ad50-11e4-85d5-ebf1c79c5e2e.png)

**Comment by hadley** [comment]
Sorry I mean one column, and either one or two rows.

Is it possible to have a non-numeric nominal/ordinal variable? What types other than numeric are possible?

**Comment by hadley** [comment]
BTW, the best workflow would be create an issue for each individual problem, attaching the simplest possible SPSS file that illustrates it. Then I can easily track my progress.  

I really appreciate the help!

**Comment by sjPlot** [comment]
I  just sent you the sample files via mail, I hope it's ok.
I have changed the interface language to English, so you can read the screenshot with the different input types:
![spss-variable-types](https://cloud.githubusercontent.com/assets/4901179/6062891/7d92ac5c-ad53-11e4-8167-c6453c1fc641.png)

As you can see, SPSS(-users) only use numeric type for continuous, ordinal or nominal variables (so factors and numeric variables are both numerically entered in SPSS).

Although you can change the variable type (see following screenshot):
![spss-types](https://cloud.githubusercontent.com/assets/4901179/6062929/d6304a4a-ad53-11e4-98f8-2be3ea9e6bc7.png)
SPSS does treat every variable as numeric. This is a confusing issue when running regression models. While R creates "dummy variables" for each factor level automatically, SPSS treats variables of type "ordinal" (factor) as numeric and does not create dummies for factors with more than two levels...

**Comment by evanmiller** [comment]
On the ReadStat side of things:

* The variable label is accessible in the `var_label` argument passed to the `readstat_handle_variable_callback`

* The value labels for a particular variable are identified with a string in the `val_labels` argument to `readstat_handle_variable_callback`. To figure out what those value labels actually are, a dictionary should be built later in the parsing with the `readstat_handle_value_label_callback`, which is called once for each label. Its args include:

  * `val_labels`: the string identifier of the label set, e.g. "yes/no"
  * `value`: a value in the label set. Could be numeric or a string
  * `label`: the string label for that value

In this way many variables can share a single set of value labels (e.g. 0 => "no", 1 => "yes"). Also a label may exist for a value that is not present in the data set. For testing I often use General Social Surveys for Stata/SPSS files, which make extensive use of both variable and value labels:

http://www3.norc.org/GSS+Website/Download/

**Comment by hadley** [comment]
@evanmiller Just to confirm, `readstat_handle_value_label_callback()` is called after `readstat_handle_variable_callback()`?

**Comment by evanmiller** [comment]
@hadley Yes. The callbacks are executed in the same order that things appear in the file. That order is:

SPSS: info, variables, value labels, data
Stata: info, variables, data, value labels

SAS is a little different in that value labels always appear in a separate sas7bcat "catalog" file, which is why there are separate `parse_sas7bdat` and `parse_sas7bcat` functions.

**Comment by hadley** [comment]
@evanmiller in what circumstances is the value value a string?

Would you normally expect the sas catalog file to have the same name (but different) extension as the main data file? Or is there one catalog file per label set?

**Comment by evanmiller** [comment]
In SPSS the value can be a short string, e.g. "M" for Male and "F" for Female. Early versions of SPSS did not allow string values longer than 8 (!) and so they implemented labels in part to get around it. That limit is gone, but one artifact is that value labels can only apply to strings of length 8 or shorter. (And to numbers, of course.)

Value labels in Stata can only apply to integer values, and not to strings or arbitrary doubles.

In SAS, value labels can apply to double values and to strings of up to 16 characters.

SAS catalog files contain multiple label sets. They do not necessarily have the same name as the main data file; from my understanding a single catalog file is often used for multiple data files. (E.g. if you administered the same survey to different groups or across different years, you might split the data across multiple data files and use one catalog file to keep the labels in sync across all of them.)

**Comment by hadley** [comment]
In R, labels are only ever associated with integer values, so if the foreign data as labelled strings, we need to use pick either the values or the labels. It looks like the existing import functions default to using the labels, so I'll do the same thing.

The R docs also mention "Occasionally in SPSS, value labels will be added to some values of a continuous variable (e.g. to distinguish different types of missing data), and you will not want these variables converted to factors.". Does that agree with your understanding?

**Comment by evanmiller** [comment]
That sounds about right, particularly for survey data. You might have "years of education" with special labeled values for "refused" and "unknown". Special values are usually negative or some version of 10^N-1.

**Comment by sjPlot** [comment]
E.g. when having age, with a theoretical range from 0 to 150, a value of 999 is used to indicate missings. You can specify missing values in SPSS, i.e. which numeric value should be considered as missing. I may send you another SPSS sample with declared missing data.

**Comment by hadley** [comment]
I'm now capturing this information in my C code and returning a new class of object called "labelled". I think this is the best approach since it doesn't lose any information, and I can add coercion functions that let you easily turn it into a factor etc.

**Comment by hadley** [comment]
@sjPlot now done. See `labelled()` for more examples of what you can do with the results. Please let me know if you discover any datasets where this approach doesn't work.

**Comment by rishabasthana5144** [comment]
I am facing the same problem. When i am reading the SPSS file, one of its attribute is getting read as in its atomic structure with value labels and not the usual factor type for categorical variable.

Any suggestions to solve this please.

**Comment by hadley** [comment]
@rishabasthana5144 file a new issue with a reproducible example created by the reprex package
