### ISSUE TITLE
Error in sprintf("%02d", m)

### ISSUE THREAD

**Issue by bethatkinson** [hadley/haven#40]
The data read in fine, but when I went to look at it I got this error message:
<pre><codes>
head(p7)
Error in sprintf("%02d", m) : 
  invalid format '%02d'; use format %f, %e, %g or %a for numeric objects
</pre></code>

In further investigation I found the variable that was causing the problem. If I remove this variable, then *head* works fine.  In sas the format and informat is TIME8. 

<pre><codes>
attributes(p7[,42])
$label
[1] "Time of highest X within 3 yrs of 7/1/2005"

$class
[1] "hms"

summary(p7[,42])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   1800   29280   31200   31020   33420   35940   32987 
</pre></codes>

**Comment by hadley** [comment]
Should be fixed now
