### ISSUE TITLE
write_sav() should set "Missings" to "none" in SPSS data file

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#42]
When writing data with missings to SPSS, the "Missing" object in the SPSS data file is empty. It better should be set to "None" (i.e., missing values are not assigned with a specific numeric value of the variable).

See screenshots. Sample data set will be sent via mail...

![clipboard01](https://cloud.githubusercontent.com/assets/4901179/6562945/7612cc2e-c69d-11e4-8d36-1437a88a6a9c.png)

**Comment by hadley** [comment]
Can you please post the data publicly somewhere and link to here? That makes life easier for me.

**Comment by sjPlot** [comment]
Ok, here it is:
https://www.dropbox.com/s/7uc505hyk284e16/seltene_diagnose_mit_ID.sav?dl=0

**Comment by sjPlot** [comment]
btw, I found this "bug" because I saved data to SPSS and did some more edits in the SPSS file and it failed to save - after I changed the empty "Missing" into "None", saving the file worked.

**Comment by sjPlot** [comment]
SPSS file with haven: https://www.dropbox.com/s/o0lrclke0vh9ew4/test_haven.sav?dl=0
SPSS file with SPSS: https://www.dropbox.com/s/w9eijzr05yp58nt/test_spss.sav?dl=0

**Comment by evanmiller** [comment]
Thanks @sjPlot. See if this commit fixes the issue:

https://github.com/WizardMac/ReadStat/commit/6362ac6215f90bb2948a82737c588ff37ff67b47

I apparently misunderstood what the missing-values field was for -- it's for the user to define (real) missing values, and doesn't need the system-missing NaN value in there.

**Comment by sjPlot** [comment]
I can't update your library inside the haven-package - when I manually replace your C-src-files inside the haven-source-code and zip the haven package, the package won't install.

I'll give you the feedback when @hadley has updated your library here.

**Comment by hadley** [comment]
@sjPlot just updated readstat so you can try it out

**Comment by sjPlot** [comment]
Yes, this seems to fix the issue! Thanks!
