### ISSUE TITLE
Missing values problem read_dta()

### ISSUE THREAD

**Issue by vectorgrid** [hadley/haven#43]
Great package. However, I have some issues reading STATA files. All the missing observations are somehow ignored, and not correctly identified. 
My example data is here: https://www.dropbox.com/s/msbz5f7d5p84k2d/BFIR21FL.zip?dl=0

Code replicating my issue:
> bfir21fl <- read_dta(path = "BFIR21FL.DTA")
> str(bfir21fl$v121)
Class 'labelled'  atomic [1:6354] 1 1 1 1 ...
  ..- attr(*, "label")= chr "has television"
  ..- attr(*, "labels")= Named int [1:2] 0 1
  .. ..- attr(*, "names")= chr [1:2] "no" "yes"
> sum(is.na(bfir21fl$v121))
[1] 0
> sum(is.na(as_factor(bfir21fl$v121)))
[1] 0

Using the read.dta from foreign results in:
> bfir21fl_1 <- read.dta("BFIR21FL.DTA")
> str(bfir21fl_1$v121)
 Factor w/ 2 levels "no","yes": 2 2 2 2 2 1 1 1 1 1 ...
> length(bfir21fl_1$v121)
[1] 6354
> sum(is.na(bfir21fl_1$v121))
[1] 61

61 is the correct result. My question is, either there is something I am doing wrong, or the conversion is not working correctly, or not according to my expectations.

**Comment by evanmiller** [comment]
@hadley this file is imported correctly with ReadStat, with 61 values identified as missing in column v121.

**Comment by evanmiller** [comment]
@hadley this file is imported correctly with ReadStat, with 61 values identified as missing in column v121.
