### ISSUE TITLE
read_sav returns "Error: `x` and `labels` must be same type" when trying to view data frame

### ISSUE THREAD

**Issue by thomasjwood** [hadley/haven#46]
I think I've found a bug in `read_sav` which only presents when I try to `View` the resultant data frame

    temp <- tempfile()
    download.file("http://www.electionstudies.org/studypages/data/anes_panel_2013_inetrecontact/anes_panel_2013_inetrecontactsav.zip",temp)
    d1 <- read_sav(unzip(temp, "anes_panel_2013_inetrecontact.sav"))

which all works fine, until I try

    View(d1)

which returns a blank data frame view, and this error message

    Error: `x` and `labels` must be same type

**Comment by sjPlot** [comment]
Seems to be the same issue as [https://github.com/hadley/haven/issues/28](this one).
