### ISSUE TITLE
Fails to load SAS dataset with Shift-JIS encoding

### ISSUE THREAD

**Issue by dramage1** [hadley/haven#47]
Hello, I have a SAS dataset that we got from an external source and it has Encoding = shift-jis  Japanese (SJIS). Haven generates this error when trying to read it: Error: Failed to parse C:\Temp\lb.sas7bdat: Invalid file, or file has unsupported features.

The problem goes away if I use PC SAS to convert the file to a local encoding, e.g,  Encoding =  wlatin1  Western (Windows). 

It is possible for Haven to support Shift-jis since on many occassions I will not have access to PC SAS to do the conversion.

Regards,
David

**Comment by hadley** [comment]
Have you tried the development version? This should be fixed there.

**Comment by dramage1** [comment]
I downloaded the development version just now but I am getting the same message. I am not sure what else could be the problem. Here is the SAS proc contents:

                                     The CONTENTS Procedure

Data Set Name        TMP.LB                                          Observations          29673
Member Type          DATA                                            Variables             28
Engine               V9                                              Indexes               0
Created              03/13/2015 18:59:50                             Observation Length    1416
Last Modified        03/13/2015 18:59:50                             Deleted Observations  0
Protection                                                           Compressed            NO
Data Set Type                                                        Sorted                NO
Label                LB and Supplemental LB
Data Representation  HP_UX_64, RS_6000_AIX_64, SOLARIS_64, HP_IA64
Encoding             shift-jis  Japanese (SJIS)


                               Engine/Host Dependent Information

                        Data Set Page Size          65536
                        Number of Data Set Pages    646
                        First Data Page             1
                        Max Obs per Page            46
                        Obs in First Data Page      42
                        Number of Data Set Repairs  0
                        Filename                    c:\temp\lb.sas7bdat
                        Release Created             9.0202M3
                        Host Created                SunOS
