### ISSUE TITLE
spss complains that columns from file made using write_sav are constant

### ISSUE THREAD

**Issue by rubenarslan** [hadley/haven#51]
even though they apparently aren't in the data view.. sorry I don't have an reproducible example, but that's what my colleague who I prepared the file for told me.

**Comment by hadley** [comment]
Please re-open if you can provide a reproducible example.

**Comment by rubenarslan** [comment]
Hi, sorry for not doing this earlier, I thought it'd be difficult and I couldn't share the original dataset. However, the error shows even using a two variable subset. It works using `cars` though.
I attached links to the data in rdata and sav format. Nothing odd about it as far as I can tell (and it's easy to examine the whole dataset). The data displays normally in SPSS v20 and does not look constant at all, but I cannot run a bivariate correlation between the two variables.
If I take only the first 50 rows, it works, if I take the first 200 of 209 it doesn't. I guess this explains why it works using cars, which has only 50 rows.

library(haven)
load("test.rda")
write_sav(example, path = "test.sav")

https://dl.dropboxusercontent.com/u/1078620/test.rda
https://dl.dropboxusercontent.com/u/1078620/test.sav

**Comment by rubenarslan** [comment]
I'm sorry, didn't notice this before. It's about missings. There's some missings on row 146, and that's what causes it. Changing the missings to some other value fixes it. After I changed them to a number, I can set them missing again and it still works.
