### ISSUE TITLE
read_spss can't deal with range of missing values in SPSS file

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#55]
When missing values span over a larger range of values, you can declare this value range as "missing" values, see:
![spss_missing_range](https://cloud.githubusercontent.com/assets/4901179/6824074/db792204-d2ee-11e4-8f07-767a8e18c1f5.png)

This differs from declaring specific values as missing, like:
![spss_missing_value](https://cloud.githubusercontent.com/assets/4901179/6824079/ebd62cb4-d2ee-11e4-999e-f91b8590b11a.png)

When loading a SPSS file with a "missing range", `read_spss` throws an error:

    > test <- read_spss("spss_missing_range.sav")
    Error: Failed to parse C:\Users\Luedeke\Desktop\spss_missing_range.sav: Invalid file, or file has unsupported features. 

I've uploaded two sample files.

SPSS-file that causes trouble (missing range):
https://www.dropbox.com/s/nkkk5mg45xknbeo/spss_missing_range.sav?dl=0

SPSS-file that works (missing values):
https://www.dropbox.com/s/dzdn38f81lk0rbx/spss_missing_value.sav?dl=0

**Comment by sjPlot** [comment]
When defining the missing range, you can also use `LO` (indicating the lowest value) and `HI` (indicating the highest value).

![spss_mis_range2](https://cloud.githubusercontent.com/assets/4901179/6824175/fe9b7d76-d2ef-11e4-91a9-6b0067ee339e.png)

https://www.dropbox.com/s/v04ldi7v0xtu62w/sample_missing_range_HI.sav?dl=0

**Comment by evanmiller** [comment]
Should be fixed in this ReadStat commit:

https://github.com/WizardMac/ReadStat/commit/c287a165ac978c2d39fd0cccdf5a32a0b506fdb8

**Comment by sjPlot** [comment]
I have tested your commit. Reading the file now works. However, the values (declared as missing range in SPSS) do not appear as NA's in the imported data frame - was this your intention?

Perhaps read_spss (or any read function) could offer whether (labelled) missing value ranges should be imported as NA or as labelled values? I would assume this is more a "design decision", so I'll close this issue.

**Comment by evanmiller** [comment]
Thanks for the update. When I import via plain ReadStat I get the same result in both sample files (missing values in rows 3 and 4) -- so the NA issue sounds to me like a haven design decision.
