### ISSUE TITLE
Option for turning on/off labelled columns (particularly Stata files)

### ISSUE THREAD

**Issue by nicholasbloom** [hadley/haven#56]
A simple request: could you add an option to turn off labelling for labeled Stata files? 

I'd be fine with one that dropped labels altogether, returning only the numeric values underlying the Stata labels. 

The main concern is that `dplyr` still doesn't support labelled data.frames, but I'm worried about compatibility with other packages, too.

**Comment by hadley** [comment]
Are you worried about variable labels or value labels?

**Comment by nicholasbloom** [comment]
Either/both. I'd be happy to have both labels if standard vector classes (e.g. numeric, character) can be preserved. But I am willing to forgo labeling of any kind that necessitates adding the class "labelled" to a variable, as with `rl$type` below:

```
> class(rl$int_date)
[1] "numeric"
> class(rl$type)
[1] "labelled"
> str(rl$type)
Class 'labelled'  atomic [1:35556] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "Type of sample used"
  ..- attr(*, "labels")= Named int [1:2] 1 2
  .. ..- attr(*, "names")= chr [1:2] "RDD" "Callback"
```

type is actually a numeric vector, but is classed "labelled." I'm envisioning it as an "unlabeled" boolean function parameter that (default can be TRUE), that, when FALSE, returns a standard vector class of that column, which would be either "numeric" or "integer" for `rl$type`. I always have a codebook to reference alongside analysis, so labels aren't that important, at least to me.

**Comment by hadley** [comment]
In that case, you should do `df[] <- lapply(df, zap_labels)`

**Comment by nicholasbloom** [comment]
Excellent. Thanks!
