### ISSUE TITLE
Error after importing Stata data

### ISSUE THREAD

**Issue by eXcuvator** [hadley/haven#59]
With the latest built, the issue linked [here](http://stackoverflow.com/questions/29570868/r-how-to-use-haven-with-somewhat-broken-data?noredirect=1#comment47296847_29570868) persists. Basically, using `df <- read_dta('LIAB_lm_9310_v1_pers.dta')`, where the data file is included in [this zip](http://doku.iab.de/fdz/liab/LIAB_LM_9310_v1_test_dta.zip), if I try to `head(df)` or `data.table(df)`, I get an error

    Error: `x` and `labels` must be same type

and in the latter case, `R` crashes subsequently.

**Comment by leeper** [comment]
I'm encountering the same error when importing from an .sav file. The traceback is:

```R
8: stop("`x` and `labels` must be same type", call. = FALSE)
7: labelled(NextMethod(), attr(x, "labels"))
6: `[.labelled`(xj, i)
5: xj[i]
4: `[.data.frame`(x, seq_len(n), , drop = FALSE)
3: x[seq_len(n), , drop = FALSE]
2: head.data.frame(dat)
1: head(dat)
```

So it's clearly related to the "labelled" class.

**Comment by dsself** [comment]
Figure I should comment this instead of keeping an open issue

With the latest cran and github version cannot filter using dplyr after importing [this .dta](https://github.com/dsself/V-dem/blob/master/Authoritarian%20Shadow/Test.dta) file using haven.

```
df <- read_dta("Authoritarian Shadow/Test.dta") %>%
  filter(year > 1996)
```
I get the error
```
Error: column 'country_name' of type character has unsupported attributes: label

**Comment by davidp6** [comment]
I've encountered this too. A quick work-around (if you don't care about the labels) is to strip the extra formatting that read_dta adds:
```R
df <- read_dta(dataFile)
df <- data.frame( do.call( 'cbind', unclass(df) ) )
```

**Comment by hadley** [comment]
@davidp6 a simpler way of doing that is:

```R
df[] <- lapply(df, unclass)
```

(plus it coerce fail if you have mixed col types)

**Comment by felixhaass** [comment]
@hadley this workaround does not fix [the problem](https://github.com/hadley/haven/issues/59#issuecomment-92540307) reported by @dsself (which I'm also experiencing) with haven 0.2.0. If apply it to @dsself's test data I'm getting `Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "list"` when trying to do `test_df %>% filter(year > 1992)` The workaround suggested by @davidp6 works, but it obviously gives back only factor columns in the resulting data frame which need to be reassigned.

**Comment by felixhaass** [comment]
Sorry for not checking earlier: Updating to the current github version of dplyr fixes the issue for me.

**Comment by LaDilettante** [comment]
Has this actually been fixed or we can only use the work around mentioned above by @hadley and @davidp6 ?

I gave haven another try today, installing from github, but ran into this same issue.

**Comment by sjkiss** [comment]
I just came across this error again. It occurred when a value label did not actually occur in the variable.
