### ISSUE TITLE
write-functions

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#6]
A really great feature would be a write function that writes back a data frame (with variable and value label attributes) to an SPSS/SAS/Stata file, where the value and variable fields are automatically set.

This would be a great benefit for all people who collaborate in teams where some use SPSS and others use R. Imagine you have a base data set (in SPSS format, because majority uses it in your department) and do some recodings and data cleaning with R, and you want to save the changes / added variables back to the SPSS data set.

I'm not sure whether this is possible at all, or if it's possible with low effort?

**Comment by hadley** [comment]
It would be great, but I think it would be a lot of effort, so is out of scope for haven.
