### ISSUE TITLE
reading unicode data 

### ISSUE THREAD

**Issue by yonicd** [hadley/haven#66]
is there a way to control the encoding of the files read by the read_sas function? I am reading sas7bdat files that have Hebrew both in the labels and in the data and it is parsing the labels as gibberish and the column data as Unicode.

> Sys.getlocale()
[1] "LC_COLLATE=Hebrew_Israel.1255;LC_CTYPE=Hebrew_Israel.1255;LC_MONETARY=Hebrew_Israel.1255;LC_NUMERIC=C;LC_TIME=Hebrew_Israel.1255"
> attributes(df$V1)
$label
[1] "........................úåéúåà 15 ïá íù"
> df$V1[1]
[1] "0536 äãåîö ìùîî"
> Encoding(df$V1[1])
[1] "UTF-8"
> enc2utf8(df$V1[1])
[1] "0536 äãåîö ìùîî"
> enc2native(df$V1[1])
[1] "0536 <U+00E4><U+00E3><U+00E5><U+00EE><U+00F6> <U+00EC><U+00F9><U+00EE><U+00EE>"

**Comment by hadley** [comment]
Could you please link to a sample file encoded with Hebrew?

**Comment by hadley** [comment]
Containing Hebrew I mean

**Comment by yonicd** [comment]
i got most of the problem fixed, now it shows the hebrew correctly in the labels but reversed in the data itself. here is a [link to data](https://github.com/yonicd/taseR/blob/master/temp.sas7bdat) with hebrew in the labels and columns

**Comment by hadley** [comment]
That link is now broken

**Comment by hadley** [comment]
Also please try with the dev version and let me know if it still fails.
