### ISSUE TITLE
Maximum Variable Label Length on write_spss()

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#68]
An issue was posted [on my GitHub page](https://github.com/sjPlot/devel/issues/25), however, the `write_spss` function in my package is just a wrapper for haven's write-function. So I guess, the issue is probably to be addressed by Hadley or @evanmiller?

Quote:
When I use the write_spss function with variable.label attributes, the labels appear to export properly into the .sav, however they are cut off after 120 characters. I believe 120 characters was the limit in previous versions of SPSS, but I was wondering if there was a way to change this limit. The labels I need are somewhat lengthy survey questions, so it's important the text isn't cut off after 120 characters, and I've had trouble finding help for this issue elsewhere.

**Comment by evanmiller** [comment]
This commit will increase the max label size to 256 characters from 120: https://github.com/WizardMac/ReadStat/commit/43cf3c7b6a359bd1c04fa18d25ddbab237a5197e

**Comment by sjPlot** [comment]
Thanks for the fast fix!
