### ISSUE TITLE
Problem with NA to SPSS

### ISSUE THREAD

**Issue by dgromer** [hadley/haven#70]
SPSS seems to have a problem with NA values written with haven. I use the following to create an SPSS file

```r
data <- data.frame(group = rep(c("a", "b"), each = 3),
                   score = c(10, 12, 14, 20, NA, 30))

haven::write_sav(data, "test.sav")
```

If I now open and run a t-test using
```
T-TEST GROUPS=group(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=score
  /CRITERIA=CI(.95).
```
I get the following output:
![spss_1](https://cloud.githubusercontent.com/assets/8123265/7722620/34d66e00-fee2-11e4-8ab8-75273a324e6e.png)

If I now go into the cell containing the missing value in SPSS' data editor and hit the delete key and rerun the analysis, everything works fine (although I have no visible change in the data editor in that cell):
![spss_2](https://cloud.githubusercontent.com/assets/8123265/7722614/280bd91c-fee2-11e4-8c9a-26dd89e32da6.png)

**Comment by hadley** [comment]
@dgromer could you please try with the dev version? I've fixed something related to missing values that is almost certainly a bug, but I don't have SPSS to test with

**Comment by dgromer** [comment]
@hadley the problem seems to be gone (tested with two data sets). Thanks!
