### ISSUE TITLE
Importing from Stata: Encoding issues

### ISSUE THREAD

**Issue by kwenzig** [hadley/haven#71]
It seems that there are some encoding issues using read_dta:
I'm working with version 0.2.0.9000. If there are non-ASCII-characters, like german Umlauts (äöüß), they seem to break. It looks like they were treated as UTF-8 by the import-function, but they are actually something like Latin-1 (or similar). I can correct the string by using
```
iconv(names(attr(*, "labels")), from="L1", to="UTF-8")
```
PS: With Stata 14 Unicode features have been introduced for the first time: http://www.stata.com/stata14/unicode/
PPS: I can provide a Stata 13 file containing Umlauts. (Stata 14 is not yet available for me.)

**Comment by hadley** [comment]
@evanmiller any thoughts?

**Comment by evanmiller** [comment]
It looks like prior to version 14 Stata used "extended ASCII", i.e. whatever the default code page on the computer was. ReadStat currently assumes it is regular ASCII, without support for umlauts and such. I'll see about adding support for specifying the encoding, since it's not stored in the DTA file itself.

**Comment by evanmiller** [comment]
Try this:

https://github.com/WizardMac/ReadStat/commit/315c8a7a3faf423fd22fce08ed53ce8f365c9930

**Comment by hadley** [comment]
@kwenzig please try with the dev version, and let us know if it still fails

**Comment by kwenzig** [comment]
I'm afraid, that there are still encoding issues. In this Stata dta file (Version 13) you see Umlauts in the variable label of make ("Mäke and Mödel") and in the contents of this string variable (1st line: "ÄMC Concörd"):
![stata](https://cloud.githubusercontent.com/assets/6614820/8331212/5b2520ea-1a87-11e5-930c-c59a212f2b1e.png)
I import the data using haven und write this information to a text file with:
```
test <- read_dta("C:/Users/kwenzig/Desktop/auto_umlaut.dta")
t1 <- test$make[1]
t2 <- attr(test$make, "label")
t12 <- paste0(t1,"-",t2)
cat(t12,
file=(con <- file("C:/temp/haven.txt", "w", encoding = "UTF-8")),
sep="", fill=FALSE, labels=NULL, append=FALSE)
close(con)
```
Then I open haven.txt using RStudio in UTF-8-mode and get:
```
<c4>MC Conc<f6>rd-M<e4>ke and M<f6>del
```
You find the Stata file here:
https://oc.diw.de/index.php/s/LM0dPQCrsMeJDJW
HTH.

**Comment by evanmiller** [comment]
ReadStat correctly converts these strings to UTF-8, so it is most likely an issue on the haven end.

**Comment by hadley** [comment]
It seems fine to me:

```R
df <- read_dta("auto_umlaut.dta")
df[1,1]
#> [1] "ÄMC Concörd"
Encoding(df[1, 1])
#> [1] "UTF-8"
```

I'd suspect something is going wrong in elsewhere in your code that modifies, writes and reads the text file.

**Comment by kwenzig** [comment]
Thanks for trying to replicate this. I tried your code with RGui and there haven works properly. Could this be an RStudio issue I should report there?
![rgui](https://cloud.githubusercontent.com/assets/6614820/8349724/7f31e4a8-1b1f-11e5-8df6-e12ed60d5482.png)
![rstudio](https://cloud.githubusercontent.com/assets/6614820/8349674/fdfe8076-1b1e-11e5-898f-71b8d9f8d59b.png)

**Comment by hadley** [comment]
It works for me in RStudio. Do you have the latest version?

**Comment by kwenzig** [comment]
Here we have Version 0.99.441 (for windows), I will ask to get v0.99.447.

**Comment by kwenzig** [comment]
Thx. v0.99.447 arrived here and I can report, that it works as expected. Great.
