### ISSUE TITLE
read_spss() doesn’t interpret dates properly

### ISSUE THREAD

**Issue by huftis** [hadley/haven#72]
The `read_spss()` function in `haven` (latest GitHub version) doesn’t interpret dates in SPSS files properly. It looks like they’re not converted to dates at all, but remain as numeric variables. Here’s an example file: http://huftis.org/nedlasting/spss/spss-dates.sav

Running the commands

    library(haven)
    d = read_spss("spss-dates.sav")
    d

the result is

             date            datetime   timemm timemmss timemmssss
    1 13638758400 2014-12-24 00:00:00 17:28:00 17:28:00   17:28:00
    2 13509676800 2010-11-21 01:02:03  1:02:00  1:02:03    1:02:03

The first column *should* contain the dates 2014-12-24 and 2010-11-21. But it actually contains the number of seconds since 14th October 1582:

    > as.Date(d$date/86400, origin="1582-10-14")
    [1] "2014-12-24" "2010-11-21"
    > as.POSIXct(d$date, origin="1582-10-14", tz="UTC")
    [1] "2014-12-24 UTC" "2010-11-21 UTC"

System information:

    Package: haven
    Version: 0.2.0.9000
    Maintainer: Hadley Wickham <hadley@rstudio.com>
    Built: R 3.2.0; x86_64-suse-linux-gnu; 2015-05-27 17:10:06 UTC; unix

    R Version:
    platform = x86_64-suse-linux-gnu
    arch = x86_64
    os = linux-gnu
    system = x86_64, linux-gnu
    status = 
    major = 3
    minor = 2.0
    year = 2015
    month = 04
    day = 16
    svn rev = 68180
    language = R
    version.string = R version 3.2.0 (2015-04-16)
    nickname = Full of Ingredients

    Locale:
    LC_CTYPE=nn_NO.UTF-8;LC_NUMERIC=C;LC_TIME=nn_NO.UTF-8;LC_COLLATE=nn_NO.UTF-8;LC_MONETARY=nn_NO.UTF-8;LC_MESSAGES=nn_NO.UTF-8;LC_PAPER=nn_NO.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=nn_NO.UTF-8;LC_IDENTIFICATION=C

    Search Path:
    .GlobalEnv, package:haven, package:stats,
    package:graphics, package:grDevices, package:utils,
    package:datasets, package:methods, Autoloads,
    package:base

**Comment by larmarange** [comment]
A similar problem seems to happen with `read_dta` and date only variables.

**Comment by hadley** [comment]
@huftis would you mind creating a version with dates 2010-01-01 & 1970-01-01 and times 0300 and 1500?

**Comment by hadley** [comment]
@larmarange could you please do the same thing with a dta file?

**Comment by hadley** [comment]
@larmarange and open a new issue?

**Comment by huftis** [comment]
I have uploaded a file with the dates and times you requested (and the original example dates/date-times/times) to http://huftis.org/nedlasting/spss/spss-dates-expanded.sav

And here’s a screenshot of how it looks in SPSS: http://huftis.org/nedlasting/spss/spss-dates-expanded.png

**Comment by larmarange** [comment]
I just updated haven to the last version and I have prepared a Stata file available at http://joseph.larmarange.net/stata_dates.dta

- Variable *date* has `%td` format and is imported correctly.
- *datetime* has `%tc` format and is imported correctly
- *date2* has `%tdCCYY-NN-DD` format, which means it's a date with custom display format. It's not imported as a date.  In fact, any format starting with `%td`, regardless of the following character should be imported as a date  (same thing with other Stata formats)
- *datetime2* has `%tC` format and seems to be imported correctly
- *year* has `%ty` format (year format). It's imported correctly as an atomic vector, containing the year
- *months*, *week*, *quarter* and *halfyear* are specific format from Stata, respectively `%tm`, `%tw`, `%tq` and `%th`. I'm not sure that there are corresponding formats available in R. So far they are imported as integers.

Do you want to re-open that issue or to opn a new issue?
