### ISSUE TITLE
write_spss() value labels where 0 is a possible value

### ISSUE THREAD

**Issue by m-dinardo** [hadley/haven#73]
I find that when writing an SPSS file with a variable that contains 0 as a level, in the resulting .sav that variable will be shifted so that the label and value for 0 is now 1, and so on.

For example

```{r test, eval=FALSE}
dummy <- data.frame(gen = c(0,1,1,0,1,0,1,1))

dummy$gen <- factor(dummy$gen, levels=c(0,1), labels=c('Female', 'Male'))

haven::write_sav(dummy, 'genderDummy.sav')
````

In the resulting .sav, "Female" takes the value of 1 and "Male" takes the value of 2, which is different than what is desired. 

There are other cases in which I need the value of 0 to have a value label. 

I'm not sure if this is a bug or if there is a workaround I am not aware of. Thanks for the help.

**Comment by dgromer** [comment]
R's `factor` method changes your 0/1 coding to 1/2, that's not caused by `write_sav`.
```r
> str(dummy$gen)
 Factor w/ 2 levels "Female","Male": 1 2 2 1 2 1 2 2
```
