### ISSUE TITLE
read_stata() fails to read Stata 14.0  file format

### ISSUE THREAD

**Issue by dalewsteele** [hadley/haven#75]
When I import the comma delimited file appended at the end, then save using Stata IC 14.0, read_stata fails to parse the resulting .dta file.  

Stata code:
import delimited using "ct_race_chd.csv"
save "ct_race_chd.dta", replace
use "ct_race_chd.dta"

Dropbox link to the file created:
https://www.dropbox.com/s/t89lbnlhlm3nslc/ct_race_chd.dta?dl=0

R code:
> library(haven)
> ct <- read_stata("ct_race_chd.dta")
Error: Failed to parse /home/dsteele/Dropbox/MOOC/ALR/ct_race_chd.dta: Invalid file, or file has unsupported features.

----------------------- ct_race_chd.csv
race,chd,freq
1,1,5
1,0,20
2,1,20
2,0,10
3,1,15
3,0,10
4,1,10
4,0,10

**Comment by dalewsteele** [comment]
If saved in Stata v12 or v13 format,  "saveold "ct_race_chd.dta", version(13) "

then haven parses without error

Seems haven is not able to parse Stata v. 14 data files.

**Comment by hadley** [comment]
@evanmiller is this a known limitation of readstat?

**Comment by evanmiller** [comment]
It's known now :-).

I previously tried adding support by studying the docs, but I haven't had an actual file to work with until now. I'll report my progress over here:

https://github.com/WizardMac/ReadStat/issues/27

**Comment by evanmiller** [comment]
Ok, the sample file now opens with ReadStat as of commit https://github.com/WizardMac/ReadStat/commit/bad9575d35391afcfb7dc02a0d902c0cd2194f4d

**Comment by dalewsteele** [comment]
fwiw, Stata provides a detailed description of the .dta format.  See:

https://www.dropbox.com/s/2hubfl23b28bsdq/dta_14.pdf?dl=0

**Comment by hadley** [comment]
@dalewsteele please try with the dev version, and let us know if it still fails

**Comment by dalewsteele** [comment]
Excellent - the example Stata 14. format file loads fine with latest dev version (haven_0.2.0.9000)
