### ISSUE TITLE
Importing dates and datetime with read_dta

### ISSUE THREAD

**Issue by larmarange** [hadley/haven#80]
I just updated haven to the last version and I have prepared a Stata file available at http://joseph.larmarange.net/stata_dates.dta

- Variable *date* has `%td` format and is imported correctly.
- *datetime* has `%tc` format and is imported correctly
- *date2* has `%tdCCYY-NN-DD` format, which means it's a date with custom display format. It's not imported as a date.  In fact, any format starting with `%td`, regardless of the following character should be imported as a date  (same thing with other Stata formats)
- *datetime2* has `%tC` format and seems to be imported correctly
- *year* has `%ty` format (year format). It's imported correctly as an atomic vector, containing the year
- *months*, *week*, *quarter* and *halfyear* are specific format from Stata, respectively `%tm`, `%tw`, `%tq` and `%th`. I'm not sure that there are corresponding formats available in R. So far they are imported as integers.

**Comment by hadley** [comment]
That should do it - let me know if you find any other formats that don't import correctly.
