### ISSUE TITLE
A dedicated package for labelled variables

### ISSUE THREAD

**Issue by larmarange** [hadley/haven#83]
The labelled class is defined in `haven`. Therefore, `haven` is required to manipulate such variables with functions as `as_factor`. In future, we could think that other import packages could also use such class. Furthermore, it could be appropriate to develop some functions to manipulate labelled variable.

Some examples:
 ```r
label(d$x) # to get the variable label
label(d$x) <- "variable label" # to modify the variable label
label(d$x, 2) # to get the value label of variable x for value 2
label(d$x, 2) <- "Yes" # to modify the value label of variable x for value 2
summary(d$x) # to present a frequency table of d$x with global percent and valid percent (taking into account declared missing values)
```

etc.

Therefore, would it be more appropriate to have a dedicated package?

**Comment by hadley** [comment]
I'm not interested in implementing such a package, but if someone else did, I'd be happy to use it in haven.
