### ISSUE TITLE
Stata 14 test

### ISSUE THREAD

**Issue by Enrico-Palazzo** [hadley/haven#85]
Dear Hadley,

finally I found some time to report the issues I have with the new dev-version of haven and Stata 14 files. After some testing, I think Stata value labels cause the problem.

Here is the report:

devtools::install_github("hadley/haven")
library(haven)
test <- read_dta("C:/Users/FB/Desktop/test2.dta")
test <- read_dta("C:/Users/FB/Desktop/test3.dta")
"Error: Failed to parse C:\Users\FB\Desktop\test3.dta: Invalid file, or file has unsupported features."

So test2.dta works but test3.dta not.

test2 includes just three variables (2byte, 1string), which do not have value labels attached. test3 includes six variables (format: byte, string, double, float) and two of them have value labels attached.

here is a link to download both files
https://www.dropbox.com/sh/oyu1wbkygl516yt/AADIgGHeJx5YgMhPiwJmFgOTa?dl=0

sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_0.2.0.9000

loaded via a namespace (and not attached):
[1] httr_0.6.1     MASS_7.3-40    tools_3.2.0    RCurl_1.95-4.6 Rcpp_0.11.5    stringr_0.6.2  bitops_1.0-6   MatchIt_2.4-21 devtools_1.7.0

I hope this helps. Sorry, I am new to github so this is written rather sloppy without markdown....

Best

Felix

**Comment by evanmiller** [comment]
Thanks for the bug report. This commit should fix the issue on the ReadStat side:

https://github.com/WizardMac/ReadStat/commit/de7e2c6858b0347cd1954172068474eede669afd

**Comment by hadley** [comment]
And now in haven. Thanks @evanmiller!
