### ISSUE TITLE
write_sav needs to coerce labels to UTF-8

### ISSUE THREAD

**Issue by larmarange** [hadley/haven#87]
An example:

```r
v1 <- labelled(c(1,1,2,3), c(éè = 1, à = 2, ï  = 3))
v2 <- c("éè", "éè", "à", "ï")
v3 <- c("ee", "ee", "a", "i")
dt <- data_frame(v1, v2, v3)
attr(dt$v1, "label") <- "a làbèl wïth acèènts"
attr(dt$v2, "label") <- "a label with no accent"
write_sav(dt, "example.sav")
```

When opening the resulting file with SPSS, it appears that:

- v2 and v3 are correct
- the value labels of v1 are not correct (i.e. they are displayed as ??, ??, ?, ? by SPSS)
- variable labels are correct

**Comment by sjPlot** [comment]
Do you have the same problems with the `write_spss` function from the **sjmisc**-package? Try to convert label attributes to factor levels (`as_factor` or `to_label`), this might work...

**Comment by larmarange** [comment]
I just tried with write_spss. Exactly the same bug with accents in value labels.

**Comment by hadley** [comment]
In the short-term, you can work around it by setting the `Encoding()` of every character vector to UTF-8. In the long-term, haven should do that for you automatically.

**Comment by hadley** [comment]
Minimal reprex:

```R
# c("éè", "à", "ï")
labels_utf8 <- c("\u00e9\u00e8", "\u00e0", "\u00ef")
labels_latin1 <- iconv(labels_utf8, "utf-8", "latin1")

v_utf8 <- labelled(3:1, setNames(1:3, labels_utf8))
v_latin1 <- labelled(3:1, setNames(1:3, labels_latin1))

roundtrip_var(v_utf8) #ok
roundtrip_var(v_latin1) # not ok
```
