### ISSUE TITLE
Labelled variable: extending rather than changing the class?

### ISSUE THREAD

**Issue by larmarange** [hadley/haven#88]
Hi,

is there a particular reason for `labelled` to produce of class `labelled` only rather than to add the class `labelled` to the original class (e.g. to produce an object with two classes like `c("labelled", "numeric")`)?

**Comment by hadley** [comment]
Because technically, "numeric", isn't a class, it's a type. See http://adv-r.had.co.nz/OO-essentials.html.

Is this causing your problems in practice?

**Comment by larmarange** [comment]
> Because technically, "numeric", isn't a class, it's a type.

You are right. ;)

> Is this causing your problems in practice?

No technical problem.

It's just a little confusing for beginners. Adding

    cat("<Labelled ", typeof(x), ">\n", sep = "")

in `print.labelled` could be useful to help them. However, this is a minor request.

**Comment by hadley** [comment]
I think you just have to understand that in R, you need both `class()` and `typeof()` to fully understand what you're looking at.
