### ISSUE TITLE
Binary SAS file compression unsupported

### ISSUE THREAD

**Issue by imanuelcostigan** [hadley/haven#89]
See https://github.com/WizardMac/ReadStat/issues/21

**Comment by hadley** [comment]
Is there a particular reason you wanted an issue here too?

**Comment by imanuelcostigan** [comment]
Two reasons:

1. Makes it easier for other users who encounter the same problem to be aware that this is a known issue
2. As a trigger for updating ReadStat library when the upstream issue is closed

**Comment by hadley** [comment]
Do you have an actual example that triggers this problem? Binary SAS compression seems to be very rare in the wild (see related readstat issue)
