### ISSUE TITLE
Importing only selected columns from SPSS files

### ISSUE THREAD

**Issue by mbojan** [hadley/haven#90]
This is a feature request.

It would be great to be able to read (at least SPSS files) and import only selected columns. A bit like the functions in the `memisc` package. SPSS files are used to distribute data from surveys which contain a lot of variables (e.g. 10k) which are never used simultaneously. Loading entire data is usualy either impossible (not enough RAM) or takes a lot of time, and is usually needed only to create a subset.

In general, I was thinking whether it would be possible to work with SPSS files a bit like with database data sources in `dplyr`, but limited to `select` and perhaps `filter` operations... It would definitely be useful for a lot of people. At this moment `foreign::read.spss` can load only whole data files, and functions in `memisc` do not support data files produced with recent versions of SPSS.

**Comment by paulb20** [comment]
Agreed. This is why I use memisc to make loading selected variables from a series of SPSS datasets possible (to pool datasets or to generate a time series).

**Comment by hadley** [comment]
Consolidating into #164
