### ISSUE TITLE
Current haven-snapshot does not recognize missings from SPSS file

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#91]
In the latest haven build, missings are no longer imported as missings when reading SPSS files.

[small example file](https://www.dropbox.com/s/4k5kce2qik4x9d3/missings_missing.sav?dl=0)

    Class 'labelled'  atomic [1:4] 2 9 2 1
      ..- attr(*, "label")= chr "9 as missing, labelled"
      ..- attr(*, "labels")= Named num [1:3] 1 2 9
      .. ..- attr(*, "names")= chr [1:3] "one" "two" "missing"
      ..- attr(*, "is_na")= logi [1:3] FALSE FALSE FALSE

Value `9` is neither converted to `NA`, nor is it "flagged" as missing by `is_na`. Is this a "work-in-progress-bug" due to the ReadStat-update?

**Comment by tklebel** [comment]
I second that – it's really inconvenient!

**Comment by krlmlr** [comment]
It looks like this is simply not implemented at the moment: https://github.com/hadley/haven/blob/8f65dbc289a30cfd651bf5b201700d4ed1d15cdc/src/DfReader.cpp#L288. Would be nice, though.

**Comment by hadley** [comment]
I think this is because I need to update my copy of the readstat API in order to get https://github.com/WizardMac/ReadStat/commit/3c71dba2c85792aa3dfdf9f8faadcab16ebb05b7
