### ISSUE TITLE
write_dta produces odd output in stata browser

### ISSUE THREAD

**Issue by kendonB** [hadley/haven#94]
![image](https://cloud.githubusercontent.com/assets/5327505/9074272/e719f9ea-3abc-11e5-9015-ce2edecef6e0.png)

![image](https://cloud.githubusercontent.com/assets/5327505/9074287/01168584-3abd-11e5-9b0f-af0bfc4efd4e.png)

**Comment by kendonB** [comment]
This one is from ``readstata13`` and seems to work fine.

![image](https://cloud.githubusercontent.com/assets/5327505/9074309/4271d38a-3abd-11e5-8c35-264822f95162.png)

**Comment by kendonB** [comment]
This is Stata V13.1 FYI.

**Comment by jjchern** [comment]
I have the same issue with Stata 12 and 11.

**Comment by tspeidel** [comment]
Same here on Stata 14:
`write_dta(dataframe, "mydir/myfile.dta") `
everything is converted to a string.  Browser in Stata behaves strangely. De-stringing in Stata seems to fix it.
