### ISSUE TITLE
Feature request: add a labels option in save_dta

### ISSUE THREAD

**Issue by kendonB** [hadley/haven#96]
Labels are one of the few remaining nicer features in stata. Would be great if the ``save_dta`` function could add stata labels.

**Comment by andrewheiss** [comment]
You can write your own function to add label attributes (which is also nice for RStudio's data viewer):

    library(dplyr)

    add_labels <- function(df, labs) {
      # Rather than fight with lapply or dplyr::mutate_each, just use a dumb for loop
      for (i in 1:ncol(df)) {
        attr(df[[i]], "label") <- labs[i]  # For haven and RStudio
      }
      
      df
    }

    set.seed(1234)
    example_data <- data_frame(var1 = rnorm(20, 0, 1), 
                               var2 = rnorm(20, 2, 5),
                               var3 = runif(20, -10, 10),
                               var4 = factor(sample(letters, 20)))

    labels_for_vars <- c("Normal", "Normal, but different", "Uniform", 
                         "A bunch of random letters")

    df_labelled <- add_labels(example_data, labels_for_vars)
    View(df_labelled)

Result:

<img width="461" alt="screen shot 2015-08-20 at 13 12 30" src="https://cloud.githubusercontent.com/assets/73663/9390117/26cc4afc-473d-11e5-91a4-e4625f680b71.png">

**Comment by larmarange** [comment]
My understanding is that the original request was about exporting variable and value labels to Stata with `write_dta`.

About manipulation of variable and value label, there is the `labelled` package (https://github.com/larmarange/labelled) designed for manipulating the `labelled` class introduced by `haven`.

**Comment by andrewheiss** [comment]
Oh, I forgot to mention that adding column labels with that `add_labels()` function works with `write_dta()`—RStudio and `haven` use the same internal column labelling conventions. 

The `labelled` package looks like a nicer, more robust version of my simple `add_labels()` function. I'll check it out.

**Comment by hadley** [comment]
Haven already writes labels out if present, so I'm going to close this issue.
