### ISSUE TITLE
write_dta not including format

### ISSUE THREAD

**Issue by andrewheiss** [hadley/haven#98]
Using R 3.2.1, haven 0.2, and Stata 14, `write_dta` does not create browsable data for Stata. All the data is present and usable in Stata, but the columns in a haven-exported file lack a format, so Stata does not display them in the browse window.

Here's a minimal example:

    library(dplyr)
    library(haven)
    library(foreign)

    set.seed(1234)
    example_data <- data_frame(var1 = rnorm(20, 0, 1), 
                               var2 = rnorm(20, 2, 5),
                               var3 = runif(20, -10, 10),
                               var4 = factor(sample(letters, 20)))

    write_dta(example_data, path="with_haven.dta")
    write.dta(example_data, file="with_foreign.dta")

With foreign, everything works well:

<img width="912" alt="with_foreign" src="https://cloud.githubusercontent.com/assets/73663/9389673/4b988786-473a-11e5-9c5b-b370de628d83.png">

With haven, there is no format (`%9.0g`) and all the columns are blank, but the data is still there (see top red box). If I add a format manually, the data displays just fine.

<img width="912" alt="with_haven" src="https://cloud.githubusercontent.com/assets/73663/9389674/4ba60b68-473a-11e5-81a8-0d6fc568bb18.png">

**Comment by evanmiller** [comment]
Fixed in ReadStat: https://github.com/WizardMac/ReadStat/commit/d41fcb6e7f99bf992dc4d4aa8837c8d4f24376c0

(Haven can override the defaults if desired)
