### ISSUE TITLE
attribute "is_na" is NULL

### ISSUE THREAD

**Issue by itsdalmo** [hadley/haven#99]
Hi,

When reading a SPSS-file (using `read_sav`), the attribute `is_na` is returned as `NULL`. This causes problems with `print.labelled`. I suppose this should be fixed in the underlying C++ (which I don't know) code, but I can create a pull request for a patchwork fix.

**Occurs in Line 87 in Labelled.R**
`lab_df <- data.frame(value = unname(labels), label = names(labels), is_na = attr(x, "is_na"))`

**Comment by hadley** [comment]
Can you please include a reproducible example, because I can't see what would be going wrong here
